// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/relab/hotstuff/core (interfaces: Consensus)
//
// Generated by this command:
//
//	mockgen -destination=../internal/mocks/consensus_mock.go -package=mocks . Consensus
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	hotstuff "github.com/relab/hotstuff"
	gomock "go.uber.org/mock/gomock"
)

// MockConsensus is a mock of Consensus interface.
type MockConsensus struct {
	ctrl     *gomock.Controller
	recorder *MockConsensusMockRecorder
	isgomock struct{}
}

// MockConsensusMockRecorder is the mock recorder for MockConsensus.
type MockConsensusMockRecorder struct {
	mock *MockConsensus
}

// NewMockConsensus creates a new mock instance.
func NewMockConsensus(ctrl *gomock.Controller) *MockConsensus {
	mock := &MockConsensus{ctrl: ctrl}
	mock.recorder = &MockConsensusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsensus) EXPECT() *MockConsensusMockRecorder {
	return m.recorder
}

// Propose mocks base method.
func (m *MockConsensus) Propose(view hotstuff.View, cert hotstuff.SyncInfo) (hotstuff.SyncInfo, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Propose", view, cert)
	ret0, _ := ret[0].(hotstuff.SyncInfo)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Propose indicates an expected call of Propose.
func (mr *MockConsensusMockRecorder) Propose(view, cert any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Propose", reflect.TypeOf((*MockConsensus)(nil).Propose), view, cert)
}

// StopVoting mocks base method.
func (m *MockConsensus) StopVoting(view hotstuff.View) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StopVoting", view)
}

// StopVoting indicates an expected call of StopVoting.
func (mr *MockConsensusMockRecorder) StopVoting(view any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopVoting", reflect.TypeOf((*MockConsensus)(nil).StopVoting), view)
}
