// Code generated by protoc-gen-gorums. DO NOT EDIT.

package proto

import (
	context "context"
	fmt "fmt"
	empty "github.com/golang/protobuf/ptypes/empty"
	gorums "github.com/relab/gorums"
	encoding "google.golang.org/grpc/encoding"
	sort "sort"
)

// A Configuration represents a static set of nodes on which quorum remote
// procedure calls may be invoked.
type Configuration struct {
	id    uint32
	nodes []*gorums.Node
	n     int
	mgr   *Manager
	qspec QuorumSpec
	errs  chan gorums.Error
}

// NewConfig returns a configuration for the given node addresses and quorum spec.
// The returned func() must be called to close the underlying connections.
// This is an experimental API.
func NewConfig(qspec QuorumSpec, opts ...gorums.ManagerOption) (*Configuration, func(), error) {
	man, err := NewManager(opts...)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to create manager: %v", err)
	}
	c, err := man.NewConfiguration(man.NodeIDs(), qspec)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to create configuration: %v", err)
	}
	return c, func() { man.Close() }, nil
}

// ID reports the identifier for the configuration.
func (c *Configuration) ID() uint32 {
	return c.id
}

// NodeIDs returns a slice containing the local ids of all the nodes in the
// configuration. IDs are returned in the same order as they were provided in
// the creation of the Configuration.
func (c *Configuration) NodeIDs() []uint32 {
	ids := make([]uint32, len(c.nodes))
	for i, node := range c.nodes {
		ids[i] = node.ID()
	}
	return ids
}

// Nodes returns a slice of each available node. IDs are returned in the same
// order as they were provided in the creation of the Configuration.
func (c *Configuration) Nodes() []*Node {
	nodes := make([]*Node, 0, len(c.nodes))
	for _, n := range c.nodes {
		nodes = append(nodes, &Node{n, c.mgr})
	}
	return nodes
}

// Size returns the number of nodes in the configuration.
func (c *Configuration) Size() int {
	return c.n
}

func (c *Configuration) String() string {
	return fmt.Sprintf("config-%d", c.id)
}

// Equal returns a boolean reporting whether a and b represents the same
// configuration.
func Equal(a, b *Configuration) bool { return a.id == b.id }

// SubError returns a channel for listening to individual node errors. Currently
// only a single listener is supported.
func (c *Configuration) SubError() <-chan gorums.Error {
	return c.errs
}

func init() {
	encoding.RegisterCodec(gorums.NewGorumsCodec(orderingMethods))
}

func NewManager(opts ...gorums.ManagerOption) (mgr *Manager, err error) {
	mgr = &Manager{}
	mgr.Manager, err = gorums.NewManager(opts...)
	if err != nil {
		return nil, err
	}
	return mgr, nil
}

type Manager struct {
	*gorums.Manager
}

func (m *Manager) NewConfiguration(ids []uint32, qspec QuorumSpec) (*Configuration, error) {
	if len(ids) == 0 {
		return nil, gorums.IllegalConfigError("need at least one node")
	}

	var nodes []*gorums.Node
	unique := make(map[uint32]struct{})
	for _, nid := range ids {
		// ensure that identical IDs are only counted once
		if _, duplicate := unique[nid]; duplicate {
			continue
		}
		unique[nid] = struct{}{}

		node, found := m.Node(nid)
		if !found {
			return nil, gorums.NodeNotFoundError(nid)
		}

		i := sort.Search(len(nodes), func(i int) bool {
			return node.ID() < nodes[i].ID()
		})
		nodes = append(nodes, nil)
		copy(nodes[i+1:], nodes[i:])
		nodes[i] = node
	}

	c := &Configuration{
		nodes: nodes,
		n:     len(nodes),
		mgr:   m,
		qspec: qspec,
	}
	return c, nil
}

// Nodes returns a slice of each available node. IDs are returned in the same
// order as they were provided in the creation of the Manager.
func (m *Manager) Nodes() []*Node {
	gorumsNodes := m.Manager.Nodes()
	nodes := make([]*Node, 0, len(gorumsNodes))
	for _, n := range gorumsNodes {
		nodes = append(nodes, &Node{n, m})
	}
	return nodes
}

type Node struct {
	*gorums.Node
	mgr *Manager
}

// Reference imports to suppress errors if they are not otherwise used.
var _ empty.Empty

// Propose is a quorum call invoked on all nodes in configuration c,
// with the same argument in, and returns a combined result.
func (c *Configuration) Propose(in *Block) {

	cd := gorums.QuorumCallData{
		Manager:  c.mgr.Manager,
		Nodes:    c.nodes,
		Message:  in,
		MethodID: proposeMethodID,
	}

	gorums.Multicast(cd)
}

// QuorumSpec is the interface of quorum functions for Hotstuff.
type QuorumSpec interface {
}

// Hotstuff is the server-side API for the Hotstuff Service
type Hotstuff interface {
	Propose(context.Context, *Block)
	Vote(context.Context, *PartialCert)
	NewView(context.Context, *QuorumCert)
}

func RegisterHotstuffServer(srv *gorums.Server, impl Hotstuff) {
	srv.RegisterHandler(proposeMethodID, func(ctx context.Context, in *gorums.Message, _ chan<- *gorums.Message) {
		req := in.Message.(*Block)
		impl.Propose(ctx, req)
	})
	srv.RegisterHandler(voteMethodID, func(ctx context.Context, in *gorums.Message, _ chan<- *gorums.Message) {
		req := in.Message.(*PartialCert)
		impl.Vote(ctx, req)
	})
	srv.RegisterHandler(newViewMethodID, func(ctx context.Context, in *gorums.Message, _ chan<- *gorums.Message) {
		req := in.Message.(*QuorumCert)
		impl.NewView(ctx, req)
	})
}

const proposeMethodID int32 = 0
const voteMethodID int32 = 1
const newViewMethodID int32 = 2

var orderingMethods = map[int32]gorums.MethodInfo{

	0: {RequestType: new(Block).ProtoReflect(), ResponseType: new(empty.Empty).ProtoReflect()},
	1: {RequestType: new(PartialCert).ProtoReflect(), ResponseType: new(empty.Empty).ProtoReflect()},
	2: {RequestType: new(QuorumCert).ProtoReflect(), ResponseType: new(empty.Empty).ProtoReflect()},
}

// Reference imports to suppress errors if they are not otherwise used.
var _ empty.Empty

// Vote is a quorum call invoked on all nodes in configuration c,
// with the same argument in, and returns a combined result.
func (n *Node) Vote(in *PartialCert) {

	cd := gorums.CallData{
		Manager:  n.mgr.Manager,
		Node:     n.Node,
		Message:  in,
		MethodID: voteMethodID,
	}

	gorums.Unicast(cd)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ empty.Empty

// NewView is a quorum call invoked on all nodes in configuration c,
// with the same argument in, and returns a combined result.
func (n *Node) NewView(in *QuorumCert) {

	cd := gorums.CallData{
		Manager:  n.mgr.Manager,
		Node:     n.Node,
		Message:  in,
		MethodID: newViewMethodID,
	}

	gorums.Unicast(cd)
}
