version: "2"
linters:
  enable:
  - gocyclo
  - misspell
  - revive
  settings:
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US
    revive:
      rules:
      - name: unexported-return
        disabled: true
      - name: unused-parameter
    staticcheck:
      checks:
      - all
  exclusions:
    generated: lax
    paths:
    - third_party$
    - builtin$
    - examples$
formatters:
  exclusions:
    generated: lax
    paths:
    - third_party$
    - builtin$
    - examples$
