// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/hotstuff.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/relab/gorums"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HSNode struct {
	ParentHash           []byte      `protobuf:"bytes,1,opt,name=ParentHash,proto3" json:"ParentHash,omitempty"`
	Command              []byte      `protobuf:"bytes,2,opt,name=Command,proto3" json:"Command,omitempty"`
	QC                   *QuorumCert `protobuf:"bytes,3,opt,name=QC,proto3" json:"QC,omitempty"`
	Height               int64       `protobuf:"varint,4,opt,name=Height,proto3" json:"Height,omitempty"`
	MsgID                uint64      `protobuf:"varint,5,opt,name=MsgID,proto3" json:"MsgID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *HSNode) Reset()         { *m = HSNode{} }
func (m *HSNode) String() string { return proto.CompactTextString(m) }
func (*HSNode) ProtoMessage()    {}
func (*HSNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_f216c1d963e599bc, []int{0}
}

func (m *HSNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HSNode.Unmarshal(m, b)
}
func (m *HSNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HSNode.Marshal(b, m, deterministic)
}
func (m *HSNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HSNode.Merge(m, src)
}
func (m *HSNode) XXX_Size() int {
	return xxx_messageInfo_HSNode.Size(m)
}
func (m *HSNode) XXX_DiscardUnknown() {
	xxx_messageInfo_HSNode.DiscardUnknown(m)
}

var xxx_messageInfo_HSNode proto.InternalMessageInfo

func (m *HSNode) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

func (m *HSNode) GetCommand() []byte {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *HSNode) GetQC() *QuorumCert {
	if m != nil {
		return m.QC
	}
	return nil
}

func (m *HSNode) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *HSNode) GetMsgID() uint64 {
	if m != nil {
		return m.MsgID
	}
	return 0
}

type PartialSig struct {
	ReplicaID            int32    `protobuf:"varint,1,opt,name=ReplicaID,proto3" json:"ReplicaID,omitempty"`
	R                    []byte   `protobuf:"bytes,2,opt,name=R,proto3" json:"R,omitempty"`
	S                    []byte   `protobuf:"bytes,3,opt,name=S,proto3" json:"S,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartialSig) Reset()         { *m = PartialSig{} }
func (m *PartialSig) String() string { return proto.CompactTextString(m) }
func (*PartialSig) ProtoMessage()    {}
func (*PartialSig) Descriptor() ([]byte, []int) {
	return fileDescriptor_f216c1d963e599bc, []int{1}
}

func (m *PartialSig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartialSig.Unmarshal(m, b)
}
func (m *PartialSig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartialSig.Marshal(b, m, deterministic)
}
func (m *PartialSig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartialSig.Merge(m, src)
}
func (m *PartialSig) XXX_Size() int {
	return xxx_messageInfo_PartialSig.Size(m)
}
func (m *PartialSig) XXX_DiscardUnknown() {
	xxx_messageInfo_PartialSig.DiscardUnknown(m)
}

var xxx_messageInfo_PartialSig proto.InternalMessageInfo

func (m *PartialSig) GetReplicaID() int32 {
	if m != nil {
		return m.ReplicaID
	}
	return 0
}

func (m *PartialSig) GetR() []byte {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *PartialSig) GetS() []byte {
	if m != nil {
		return m.S
	}
	return nil
}

type PartialCert struct {
	Sig                  *PartialSig `protobuf:"bytes,1,opt,name=Sig,proto3" json:"Sig,omitempty"`
	Hash                 []byte      `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
	MsgID                uint64      `protobuf:"varint,3,opt,name=MsgID,proto3" json:"MsgID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PartialCert) Reset()         { *m = PartialCert{} }
func (m *PartialCert) String() string { return proto.CompactTextString(m) }
func (*PartialCert) ProtoMessage()    {}
func (*PartialCert) Descriptor() ([]byte, []int) {
	return fileDescriptor_f216c1d963e599bc, []int{2}
}

func (m *PartialCert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartialCert.Unmarshal(m, b)
}
func (m *PartialCert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartialCert.Marshal(b, m, deterministic)
}
func (m *PartialCert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartialCert.Merge(m, src)
}
func (m *PartialCert) XXX_Size() int {
	return xxx_messageInfo_PartialCert.Size(m)
}
func (m *PartialCert) XXX_DiscardUnknown() {
	xxx_messageInfo_PartialCert.DiscardUnknown(m)
}

var xxx_messageInfo_PartialCert proto.InternalMessageInfo

func (m *PartialCert) GetSig() *PartialSig {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *PartialCert) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *PartialCert) GetMsgID() uint64 {
	if m != nil {
		return m.MsgID
	}
	return 0
}

type QuorumCert struct {
	Sigs                 []*PartialSig `protobuf:"bytes,1,rep,name=Sigs,proto3" json:"Sigs,omitempty"`
	Hash                 []byte        `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *QuorumCert) Reset()         { *m = QuorumCert{} }
func (m *QuorumCert) String() string { return proto.CompactTextString(m) }
func (*QuorumCert) ProtoMessage()    {}
func (*QuorumCert) Descriptor() ([]byte, []int) {
	return fileDescriptor_f216c1d963e599bc, []int{3}
}

func (m *QuorumCert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuorumCert.Unmarshal(m, b)
}
func (m *QuorumCert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuorumCert.Marshal(b, m, deterministic)
}
func (m *QuorumCert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuorumCert.Merge(m, src)
}
func (m *QuorumCert) XXX_Size() int {
	return xxx_messageInfo_QuorumCert.Size(m)
}
func (m *QuorumCert) XXX_DiscardUnknown() {
	xxx_messageInfo_QuorumCert.DiscardUnknown(m)
}

var xxx_messageInfo_QuorumCert proto.InternalMessageInfo

func (m *QuorumCert) GetSigs() []*PartialSig {
	if m != nil {
		return m.Sigs
	}
	return nil
}

func (m *QuorumCert) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_f216c1d963e599bc, []int{4}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*HSNode)(nil), "proto.HSNode")
	proto.RegisterType((*PartialSig)(nil), "proto.PartialSig")
	proto.RegisterType((*PartialCert)(nil), "proto.PartialCert")
	proto.RegisterType((*QuorumCert)(nil), "proto.QuorumCert")
	proto.RegisterType((*Empty)(nil), "proto.Empty")
}

func init() {
	proto.RegisterFile("proto/hotstuff.proto", fileDescriptor_f216c1d963e599bc)
}

var fileDescriptor_f216c1d963e599bc = []byte{
	// 385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x92, 0x4f, 0x6e, 0xda, 0x40,
	0x14, 0xc6, 0x35, 0xd8, 0xc6, 0xed, 0x83, 0x2e, 0xfa, 0x84, 0xd0, 0x08, 0x55, 0x6d, 0x71, 0x5b,
	0x09, 0x75, 0x81, 0x2b, 0x7a, 0x83, 0xd2, 0x3f, 0xee, 0xa2, 0x08, 0xc6, 0x52, 0x17, 0x51, 0x36,
	0x06, 0x06, 0xdb, 0x12, 0x66, 0x2c, 0x7b, 0x2c, 0x94, 0x5d, 0xee, 0x90, 0x4b, 0xe4, 0x02, 0x6c,
	0xb2, 0xcc, 0x95, 0x72, 0x81, 0x8c, 0xc7, 0x46, 0x26, 0x82, 0xd5, 0xf8, 0x7b, 0xef, 0xf3, 0xef,
	0x7d, 0xf6, 0x1b, 0xe8, 0xa5, 0x99, 0x90, 0xc2, 0x8d, 0x84, 0xcc, 0x65, 0xb1, 0xd9, 0x8c, 0xb5,
	0x44, 0x4b, 0x1f, 0x83, 0xcf, 0x61, 0x2c, 0xa3, 0x62, 0x39, 0x5e, 0x89, 0xc4, 0xcd, 0xf8, 0x36,
	0x58, 0xba, 0xa1, 0xc8, 0x8a, 0x24, 0xaf, 0x8f, 0xca, 0xec, 0xdc, 0x11, 0x68, 0x7b, 0xfe, 0x4c,
	0xac, 0x39, 0xbe, 0x07, 0x98, 0x07, 0x19, 0xdf, 0x49, 0x2f, 0xc8, 0x23, 0x4a, 0x3e, 0x92, 0x51,
	0x97, 0x9d, 0x54, 0x90, 0x82, 0x3d, 0x15, 0x49, 0x12, 0xec, 0xd6, 0xb4, 0xa5, 0x9b, 0x47, 0x89,
	0x43, 0x68, 0x2d, 0xa6, 0xd4, 0x50, 0xc5, 0xce, 0xe4, 0x6d, 0x05, 0x1e, 0x2f, 0x8a, 0x72, 0xcc,
	0x94, 0x67, 0x92, 0xa9, 0x26, 0xf6, 0xd5, 0x18, 0x1e, 0x87, 0x91, 0xa4, 0xa6, 0xb2, 0x19, 0xac,
	0x56, 0xd8, 0x03, 0xeb, 0x5f, 0x1e, 0xfe, 0xfd, 0x49, 0x2d, 0x55, 0x36, 0x59, 0x25, 0x9c, 0xdf,
	0x3a, 0x8a, 0x8c, 0x83, 0xad, 0x1f, 0x87, 0xf8, 0x0e, 0x5e, 0x33, 0x9e, 0x6e, 0xe3, 0x55, 0xa0,
	0x7c, 0x65, 0x2e, 0x8b, 0x35, 0x05, 0xec, 0x02, 0x61, 0x75, 0x20, 0xc2, 0x4a, 0xe5, 0xeb, 0x24,
	0x4a, 0xf9, 0xce, 0x35, 0x74, 0x6a, 0x4e, 0x19, 0x04, 0x3f, 0x81, 0xa1, 0x78, 0x1a, 0xd1, 0x04,
	0x6d, 0x06, 0xb1, 0xb2, 0x8b, 0x08, 0xa6, 0xfe, 0x01, 0x15, 0x52, 0x3f, 0x37, 0x29, 0x8d, 0xd3,
	0x94, 0x7f, 0x00, 0x9a, 0xaf, 0xc4, 0x2f, 0x60, 0xaa, 0xd7, 0x73, 0x45, 0x37, 0x2e, 0xd3, 0x75,
	0xfb, 0x12, 0xde, 0xb1, 0xc1, 0xfa, 0x95, 0xa4, 0xf2, 0x66, 0x72, 0x4b, 0xe0, 0x95, 0x57, 0x6f,
	0x13, 0x3d, 0xb0, 0xe7, 0x99, 0x48, 0x45, 0xce, 0xf1, 0x4d, 0x4d, 0xab, 0x36, 0x35, 0xc0, 0x97,
	0xf0, 0x72, 0xbc, 0xd3, 0xbf, 0x3f, 0x50, 0xf2, 0x70, 0xa0, 0x55, 0xb6, 0xc7, 0x27, 0x5a, 0x21,
	0x47, 0xe4, 0x1b, 0xc1, 0xaf, 0x60, 0xcf, 0xf8, 0xfe, 0x7f, 0xcc, 0xf7, 0x78, 0xbe, 0x9e, 0x41,
	0xb7, 0x2e, 0x69, 0xff, 0x8f, 0xe1, 0xd5, 0x87, 0xb3, 0x8b, 0x73, 0xbc, 0x60, 0xae, 0x36, 0x2e,
	0xdb, 0xfa, 0xf8, 0xfe, 0x1c, 0x00, 0x00, 0xff, 0xff, 0x1a, 0x22, 0xaa, 0xc7, 0x7f, 0x02, 0x00,
	0x00,
}
