// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/proto/clientpb/client.proto

package clientpb

import (
	_ "github.com/relab/gorums"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Command is the request that is sent to the HotStuff replicas with the data to
// be executed.
type Command struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientID       uint32                 `protobuf:"varint,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	SequenceNumber uint64                 `protobuf:"varint,2,opt,name=SequenceNumber,proto3" json:"SequenceNumber,omitempty"`
	Data           []byte                 `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_internal_proto_clientpb_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_clientpb_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_internal_proto_clientpb_client_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetClientID() uint32 {
	if x != nil {
		return x.ClientID
	}
	return 0
}

func (x *Command) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *Command) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Batch is a list of commands to be executed
type Batch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*Command             `protobuf:"bytes,1,rep,name=Commands,proto3" json:"Commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Batch) Reset() {
	*x = Batch{}
	mi := &file_internal_proto_clientpb_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_clientpb_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_internal_proto_clientpb_client_proto_rawDescGZIP(), []int{1}
}

func (x *Batch) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

var File_internal_proto_clientpb_client_proto protoreflect.FileDescriptor

const file_internal_proto_clientpb_client_proto_rawDesc = "" +
	"\n" +
	"$internal/proto/clientpb/client.proto\x12\bclientpb\x1a\fgorums.proto\x1a\x1bgoogle/protobuf/empty.proto\"a\n" +
	"\aCommand\x12\x1a\n" +
	"\bClientID\x18\x01 \x01(\rR\bClientID\x12&\n" +
	"\x0eSequenceNumber\x18\x02 \x01(\x04R\x0eSequenceNumber\x12\x12\n" +
	"\x04Data\x18\x03 \x01(\fR\x04Data\"6\n" +
	"\x05Batch\x12-\n" +
	"\bCommands\x18\x01 \x03(\v2\x11.clientpb.CommandR\bCommands2L\n" +
	"\x06Client\x12B\n" +
	"\vExecCommand\x12\x11.clientpb.Command\x1a\x16.google.protobuf.Empty\"\b\xa0\xb5\x18\x01е\x18\x01B3Z1github.com/relab/hotstuff/internal/proto/clientpbb\x06proto3"

var (
	file_internal_proto_clientpb_client_proto_rawDescOnce sync.Once
	file_internal_proto_clientpb_client_proto_rawDescData []byte
)

func file_internal_proto_clientpb_client_proto_rawDescGZIP() []byte {
	file_internal_proto_clientpb_client_proto_rawDescOnce.Do(func() {
		file_internal_proto_clientpb_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_clientpb_client_proto_rawDesc), len(file_internal_proto_clientpb_client_proto_rawDesc)))
	})
	return file_internal_proto_clientpb_client_proto_rawDescData
}

var file_internal_proto_clientpb_client_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_clientpb_client_proto_goTypes = []any{
	(*Command)(nil),       // 0: clientpb.Command
	(*Batch)(nil),         // 1: clientpb.Batch
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_internal_proto_clientpb_client_proto_depIdxs = []int32{
	0, // 0: clientpb.Batch.Commands:type_name -> clientpb.Command
	0, // 1: clientpb.Client.ExecCommand:input_type -> clientpb.Command
	2, // 2: clientpb.Client.ExecCommand:output_type -> google.protobuf.Empty
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_clientpb_client_proto_init() }
func file_internal_proto_clientpb_client_proto_init() {
	if File_internal_proto_clientpb_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_clientpb_client_proto_rawDesc), len(file_internal_proto_clientpb_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_clientpb_client_proto_goTypes,
		DependencyIndexes: file_internal_proto_clientpb_client_proto_depIdxs,
		MessageInfos:      file_internal_proto_clientpb_client_proto_msgTypes,
	}.Build()
	File_internal_proto_clientpb_client_proto = out.File
	file_internal_proto_clientpb_client_proto_goTypes = nil
	file_internal_proto_clientpb_client_proto_depIdxs = nil
}
