// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: internal/proto/twinspb/twins.proto

package twinspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReplicaID uint32 `protobuf:"varint,1,opt,name=ReplicaID,proto3" json:"ReplicaID,omitempty"`
	NetworkID uint32 `protobuf:"varint,2,opt,name=NetworkID,proto3" json:"NetworkID,omitempty"`
}

func (x *NodeID) Reset() {
	*x = NodeID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_twinspb_twins_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeID) ProtoMessage() {}

func (x *NodeID) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_twinspb_twins_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeID.ProtoReflect.Descriptor instead.
func (*NodeID) Descriptor() ([]byte, []int) {
	return file_internal_proto_twinspb_twins_proto_rawDescGZIP(), []int{0}
}

func (x *NodeID) GetReplicaID() uint32 {
	if x != nil {
		return x.ReplicaID
	}
	return 0
}

func (x *NodeID) GetNetworkID() uint32 {
	if x != nil {
		return x.NetworkID
	}
	return 0
}

type Partition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*NodeID `protobuf:"bytes,1,rep,name=Nodes,proto3" json:"Nodes,omitempty"`
}

func (x *Partition) Reset() {
	*x = Partition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_twinspb_twins_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Partition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Partition) ProtoMessage() {}

func (x *Partition) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_twinspb_twins_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Partition.ProtoReflect.Descriptor instead.
func (*Partition) Descriptor() ([]byte, []int) {
	return file_internal_proto_twinspb_twins_proto_rawDescGZIP(), []int{1}
}

func (x *Partition) GetNodes() []*NodeID {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type View struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Leader     uint32       `protobuf:"varint,1,opt,name=Leader,proto3" json:"Leader,omitempty"`
	Partitions []*Partition `protobuf:"bytes,2,rep,name=Partitions,proto3" json:"Partitions,omitempty"`
}

func (x *View) Reset() {
	*x = View{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_twinspb_twins_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *View) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*View) ProtoMessage() {}

func (x *View) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_twinspb_twins_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use View.ProtoReflect.Descriptor instead.
func (*View) Descriptor() ([]byte, []int) {
	return file_internal_proto_twinspb_twins_proto_rawDescGZIP(), []int{2}
}

func (x *View) GetLeader() uint32 {
	if x != nil {
		return x.Leader
	}
	return 0
}

func (x *View) GetPartitions() []*Partition {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type Scenario struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*NodeID `protobuf:"bytes,1,rep,name=Nodes,proto3" json:"Nodes,omitempty"`
	Views []*View   `protobuf:"bytes,2,rep,name=Views,proto3" json:"Views,omitempty"`
}

func (x *Scenario) Reset() {
	*x = Scenario{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_twinspb_twins_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Scenario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scenario) ProtoMessage() {}

func (x *Scenario) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_twinspb_twins_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scenario.ProtoReflect.Descriptor instead.
func (*Scenario) Descriptor() ([]byte, []int) {
	return file_internal_proto_twinspb_twins_proto_rawDescGZIP(), []int{3}
}

func (x *Scenario) GetNodes() []*NodeID {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Scenario) GetViews() []*View {
	if x != nil {
		return x.Views
	}
	return nil
}

type GeneratorSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Replicas  uint32 `protobuf:"varint,1,opt,name=Replicas,proto3" json:"Replicas,omitempty"`
	Twins     uint32 `protobuf:"varint,2,opt,name=Twins,proto3" json:"Twins,omitempty"`
	Rounds    uint32 `protobuf:"varint,3,opt,name=Rounds,proto3" json:"Rounds,omitempty"`
	Shuffle   bool   `protobuf:"varint,4,opt,name=Shuffle,proto3" json:"Shuffle,omitempty"`
	Seed      int64  `protobuf:"varint,5,opt,name=Seed,proto3" json:"Seed,omitempty"`
	Consensus string `protobuf:"bytes,6,opt,name=Consensus,proto3" json:"Consensus,omitempty"`
}

func (x *GeneratorSettings) Reset() {
	*x = GeneratorSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_twinspb_twins_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneratorSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratorSettings) ProtoMessage() {}

func (x *GeneratorSettings) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_twinspb_twins_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratorSettings.ProtoReflect.Descriptor instead.
func (*GeneratorSettings) Descriptor() ([]byte, []int) {
	return file_internal_proto_twinspb_twins_proto_rawDescGZIP(), []int{4}
}

func (x *GeneratorSettings) GetReplicas() uint32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *GeneratorSettings) GetTwins() uint32 {
	if x != nil {
		return x.Twins
	}
	return 0
}

func (x *GeneratorSettings) GetRounds() uint32 {
	if x != nil {
		return x.Rounds
	}
	return 0
}

func (x *GeneratorSettings) GetShuffle() bool {
	if x != nil {
		return x.Shuffle
	}
	return false
}

func (x *GeneratorSettings) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *GeneratorSettings) GetConsensus() string {
	if x != nil {
		return x.Consensus
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Safe     bool      `protobuf:"varint,1,opt,name=Safe,proto3" json:"Safe,omitempty"`
	Commits  uint32    `protobuf:"varint,2,opt,name=Commits,proto3" json:"Commits,omitempty"`
	Scenario *Scenario `protobuf:"bytes,3,opt,name=Scenario,proto3" json:"Scenario,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_twinspb_twins_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_twinspb_twins_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_internal_proto_twinspb_twins_proto_rawDescGZIP(), []int{5}
}

func (x *Result) GetSafe() bool {
	if x != nil {
		return x.Safe
	}
	return false
}

func (x *Result) GetCommits() uint32 {
	if x != nil {
		return x.Commits
	}
	return 0
}

func (x *Result) GetScenario() *Scenario {
	if x != nil {
		return x.Scenario
	}
	return nil
}

var File_internal_proto_twinspb_twins_proto protoreflect.FileDescriptor

var file_internal_proto_twinspb_twins_proto_rawDesc = []byte{
	0x0a, 0x22, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x74, 0x77, 0x69, 0x6e, 0x73, 0x70, 0x62, 0x2f, 0x74, 0x77, 0x69, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x77, 0x69, 0x6e, 0x73, 0x22, 0x44, 0x0a, 0x06, 0x4e,
	0x6f, 0x64, 0x65, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49,
	0x44, 0x22, 0x30, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23,
	0x0a, 0x05, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x74, 0x77, 0x69, 0x6e, 0x73, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x52, 0x05, 0x4e, 0x6f,
	0x64, 0x65, 0x73, 0x22, 0x50, 0x0a, 0x04, 0x56, 0x69, 0x65, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x4c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x4c, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x0a, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x77, 0x69, 0x6e, 0x73, 0x2e,
	0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x50, 0x61, 0x72, 0x74, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x52, 0x0a, 0x08, 0x53, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69,
	0x6f, 0x12, 0x23, 0x0a, 0x05, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x74, 0x77, 0x69, 0x6e, 0x73, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x52,
	0x05, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x05, 0x56, 0x69, 0x65, 0x77, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x77, 0x69, 0x6e, 0x73, 0x2e, 0x56, 0x69,
	0x65, 0x77, 0x52, 0x05, 0x56, 0x69, 0x65, 0x77, 0x73, 0x22, 0xa9, 0x01, 0x0a, 0x11, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x77, 0x69, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x54, 0x77, 0x69, 0x6e,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x68, 0x75,
	0x66, 0x66, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x68, 0x75, 0x66,
	0x66, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x65, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x53, 0x65, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x73, 0x65,
	0x6e, 0x73, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x6f, 0x6e, 0x73,
	0x65, 0x6e, 0x73, 0x75, 0x73, 0x22, 0x63, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x53, 0x61, 0x66, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x53,
	0x61, 0x66, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73, 0x12, 0x2b, 0x0a,
	0x08, 0x53, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x74, 0x77, 0x69, 0x6e, 0x73, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f,
	0x52, 0x08, 0x53, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x6c, 0x61, 0x62, 0x2f, 0x68,
	0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x77, 0x69, 0x6e, 0x73, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_twinspb_twins_proto_rawDescOnce sync.Once
	file_internal_proto_twinspb_twins_proto_rawDescData = file_internal_proto_twinspb_twins_proto_rawDesc
)

func file_internal_proto_twinspb_twins_proto_rawDescGZIP() []byte {
	file_internal_proto_twinspb_twins_proto_rawDescOnce.Do(func() {
		file_internal_proto_twinspb_twins_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_twinspb_twins_proto_rawDescData)
	})
	return file_internal_proto_twinspb_twins_proto_rawDescData
}

var file_internal_proto_twinspb_twins_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_proto_twinspb_twins_proto_goTypes = []interface{}{
	(*NodeID)(nil),            // 0: twins.NodeID
	(*Partition)(nil),         // 1: twins.Partition
	(*View)(nil),              // 2: twins.View
	(*Scenario)(nil),          // 3: twins.Scenario
	(*GeneratorSettings)(nil), // 4: twins.GeneratorSettings
	(*Result)(nil),            // 5: twins.Result
}
var file_internal_proto_twinspb_twins_proto_depIdxs = []int32{
	0, // 0: twins.Partition.Nodes:type_name -> twins.NodeID
	1, // 1: twins.View.Partitions:type_name -> twins.Partition
	0, // 2: twins.Scenario.Nodes:type_name -> twins.NodeID
	2, // 3: twins.Scenario.Views:type_name -> twins.View
	3, // 4: twins.Result.Scenario:type_name -> twins.Scenario
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_proto_twinspb_twins_proto_init() }
func file_internal_proto_twinspb_twins_proto_init() {
	if File_internal_proto_twinspb_twins_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_twinspb_twins_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_twinspb_twins_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Partition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_twinspb_twins_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*View); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_twinspb_twins_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Scenario); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_twinspb_twins_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeneratorSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_twinspb_twins_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_twinspb_twins_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_twinspb_twins_proto_goTypes,
		DependencyIndexes: file_internal_proto_twinspb_twins_proto_depIdxs,
		MessageInfos:      file_internal_proto_twinspb_twins_proto_msgTypes,
	}.Build()
	File_internal_proto_twinspb_twins_proto = out.File
	file_internal_proto_twinspb_twins_proto_rawDesc = nil
	file_internal_proto_twinspb_twins_proto_goTypes = nil
	file_internal_proto_twinspb_twins_proto_depIdxs = nil
}
