// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: internal/proto/hotstuffpb/hotstuff.proto

package hotstuffpb

import (
	_ "github.com/relab/gorums"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PipelineBundleOfProposals struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Proposals []*PipelinedProposal `protobuf:"bytes,1,rep,name=Proposals,proto3" json:"Proposals,omitempty"`
}

func (x *PipelineBundleOfProposals) Reset() {
	*x = PipelineBundleOfProposals{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineBundleOfProposals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineBundleOfProposals) ProtoMessage() {}

func (x *PipelineBundleOfProposals) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineBundleOfProposals.ProtoReflect.Descriptor instead.
func (*PipelineBundleOfProposals) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{0}
}

func (x *PipelineBundleOfProposals) GetProposals() []*PipelinedProposal {
	if x != nil {
		return x.Proposals
	}
	return nil
}

type PipelinedProposal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PipelineId uint32    `protobuf:"varint,1,opt,name=PipelineId,proto3" json:"PipelineId,omitempty"`
	Proposal   *Proposal `protobuf:"bytes,2,opt,name=Proposal,proto3" json:"Proposal,omitempty"`
}

func (x *PipelinedProposal) Reset() {
	*x = PipelinedProposal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelinedProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelinedProposal) ProtoMessage() {}

func (x *PipelinedProposal) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelinedProposal.ProtoReflect.Descriptor instead.
func (*PipelinedProposal) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{1}
}

func (x *PipelinedProposal) GetPipelineId() uint32 {
	if x != nil {
		return x.PipelineId
	}
	return 0
}

func (x *PipelinedProposal) GetProposal() *Proposal {
	if x != nil {
		return x.Proposal
	}
	return nil
}

type Proposal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block *Block `protobuf:"bytes,1,opt,name=Block,proto3" json:"Block,omitempty"`
	AggQC *AggQC `protobuf:"bytes,2,opt,name=AggQC,proto3" json:"AggQC,omitempty"`
}

func (x *Proposal) Reset() {
	*x = Proposal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Proposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposal) ProtoMessage() {}

func (x *Proposal) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proposal.ProtoReflect.Descriptor instead.
func (*Proposal) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{2}
}

func (x *Proposal) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *Proposal) GetAggQC() *AggQC {
	if x != nil {
		return x.AggQC
	}
	return nil
}

type BlockHash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash []byte `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
}

func (x *BlockHash) Reset() {
	*x = BlockHash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHash) ProtoMessage() {}

func (x *BlockHash) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHash.ProtoReflect.Descriptor instead.
func (*BlockHash) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{3}
}

func (x *BlockHash) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parent   []byte      `protobuf:"bytes,1,opt,name=Parent,proto3" json:"Parent,omitempty"`
	QC       *QuorumCert `protobuf:"bytes,2,opt,name=QC,proto3" json:"QC,omitempty"`
	View     uint64      `protobuf:"varint,3,opt,name=View,proto3" json:"View,omitempty"`
	Command  []byte      `protobuf:"bytes,4,opt,name=Command,proto3" json:"Command,omitempty"`
	Proposer uint32      `protobuf:"varint,5,opt,name=Proposer,proto3" json:"Proposer,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{4}
}

func (x *Block) GetParent() []byte {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *Block) GetQC() *QuorumCert {
	if x != nil {
		return x.QC
	}
	return nil
}

func (x *Block) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *Block) GetCommand() []byte {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Block) GetProposer() uint32 {
	if x != nil {
		return x.Proposer
	}
	return 0
}

type ECDSASignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signer uint32 `protobuf:"varint,1,opt,name=Signer,proto3" json:"Signer,omitempty"`
	R      []byte `protobuf:"bytes,2,opt,name=R,proto3" json:"R,omitempty"`
	S      []byte `protobuf:"bytes,3,opt,name=S,proto3" json:"S,omitempty"`
}

func (x *ECDSASignature) Reset() {
	*x = ECDSASignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECDSASignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECDSASignature) ProtoMessage() {}

func (x *ECDSASignature) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECDSASignature.ProtoReflect.Descriptor instead.
func (*ECDSASignature) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{5}
}

func (x *ECDSASignature) GetSigner() uint32 {
	if x != nil {
		return x.Signer
	}
	return 0
}

func (x *ECDSASignature) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *ECDSASignature) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

type BLS12Signature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sig []byte `protobuf:"bytes,1,opt,name=Sig,proto3" json:"Sig,omitempty"`
}

func (x *BLS12Signature) Reset() {
	*x = BLS12Signature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BLS12Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BLS12Signature) ProtoMessage() {}

func (x *BLS12Signature) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BLS12Signature.ProtoReflect.Descriptor instead.
func (*BLS12Signature) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{6}
}

func (x *BLS12Signature) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type EDDSASignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signer uint32 `protobuf:"varint,1,opt,name=Signer,proto3" json:"Signer,omitempty"`
	Sig    []byte `protobuf:"bytes,2,opt,name=Sig,proto3" json:"Sig,omitempty"`
}

func (x *EDDSASignature) Reset() {
	*x = EDDSASignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EDDSASignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EDDSASignature) ProtoMessage() {}

func (x *EDDSASignature) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EDDSASignature.ProtoReflect.Descriptor instead.
func (*EDDSASignature) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{7}
}

func (x *EDDSASignature) GetSigner() uint32 {
	if x != nil {
		return x.Signer
	}
	return 0
}

func (x *EDDSASignature) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type Signature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Sig:
	//
	//	*Signature_ECDSASig
	//	*Signature_BLS12Sig
	//	*Signature_EDDSASig
	Sig isSignature_Sig `protobuf_oneof:"Sig"`
}

func (x *Signature) Reset() {
	*x = Signature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{8}
}

func (m *Signature) GetSig() isSignature_Sig {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (x *Signature) GetECDSASig() *ECDSASignature {
	if x, ok := x.GetSig().(*Signature_ECDSASig); ok {
		return x.ECDSASig
	}
	return nil
}

func (x *Signature) GetBLS12Sig() *BLS12Signature {
	if x, ok := x.GetSig().(*Signature_BLS12Sig); ok {
		return x.BLS12Sig
	}
	return nil
}

func (x *Signature) GetEDDSASig() *EDDSASignature {
	if x, ok := x.GetSig().(*Signature_EDDSASig); ok {
		return x.EDDSASig
	}
	return nil
}

type isSignature_Sig interface {
	isSignature_Sig()
}

type Signature_ECDSASig struct {
	ECDSASig *ECDSASignature `protobuf:"bytes,1,opt,name=ECDSASig,proto3,oneof"`
}

type Signature_BLS12Sig struct {
	BLS12Sig *BLS12Signature `protobuf:"bytes,2,opt,name=BLS12Sig,proto3,oneof"`
}

type Signature_EDDSASig struct {
	EDDSASig *EDDSASignature `protobuf:"bytes,3,opt,name=EDDSASig,proto3,oneof"`
}

func (*Signature_ECDSASig) isSignature_Sig() {}

func (*Signature_BLS12Sig) isSignature_Sig() {}

func (*Signature_EDDSASig) isSignature_Sig() {}

type PartialCert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sig  *QuorumSignature `protobuf:"bytes,1,opt,name=Sig,proto3" json:"Sig,omitempty"`
	Hash []byte           `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
}

func (x *PartialCert) Reset() {
	*x = PartialCert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartialCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialCert) ProtoMessage() {}

func (x *PartialCert) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialCert.ProtoReflect.Descriptor instead.
func (*PartialCert) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{9}
}

func (x *PartialCert) GetSig() *QuorumSignature {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *PartialCert) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type ECDSAMultiSignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sigs []*ECDSASignature `protobuf:"bytes,1,rep,name=Sigs,proto3" json:"Sigs,omitempty"`
}

func (x *ECDSAMultiSignature) Reset() {
	*x = ECDSAMultiSignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECDSAMultiSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECDSAMultiSignature) ProtoMessage() {}

func (x *ECDSAMultiSignature) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECDSAMultiSignature.ProtoReflect.Descriptor instead.
func (*ECDSAMultiSignature) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{10}
}

func (x *ECDSAMultiSignature) GetSigs() []*ECDSASignature {
	if x != nil {
		return x.Sigs
	}
	return nil
}

type EDDSAMultiSignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sigs []*EDDSASignature `protobuf:"bytes,1,rep,name=Sigs,proto3" json:"Sigs,omitempty"`
}

func (x *EDDSAMultiSignature) Reset() {
	*x = EDDSAMultiSignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EDDSAMultiSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EDDSAMultiSignature) ProtoMessage() {}

func (x *EDDSAMultiSignature) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EDDSAMultiSignature.ProtoReflect.Descriptor instead.
func (*EDDSAMultiSignature) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{11}
}

func (x *EDDSAMultiSignature) GetSigs() []*EDDSASignature {
	if x != nil {
		return x.Sigs
	}
	return nil
}

type BLS12AggregateSignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sig          []byte `protobuf:"bytes,1,opt,name=Sig,proto3" json:"Sig,omitempty"`
	Participants []byte `protobuf:"bytes,2,opt,name=participants,proto3" json:"participants,omitempty"`
}

func (x *BLS12AggregateSignature) Reset() {
	*x = BLS12AggregateSignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BLS12AggregateSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BLS12AggregateSignature) ProtoMessage() {}

func (x *BLS12AggregateSignature) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BLS12AggregateSignature.ProtoReflect.Descriptor instead.
func (*BLS12AggregateSignature) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{12}
}

func (x *BLS12AggregateSignature) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *BLS12AggregateSignature) GetParticipants() []byte {
	if x != nil {
		return x.Participants
	}
	return nil
}

type QuorumSignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Sig:
	//
	//	*QuorumSignature_ECDSASigs
	//	*QuorumSignature_BLS12Sig
	//	*QuorumSignature_EDDSASigs
	Sig isQuorumSignature_Sig `protobuf_oneof:"Sig"`
}

func (x *QuorumSignature) Reset() {
	*x = QuorumSignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuorumSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumSignature) ProtoMessage() {}

func (x *QuorumSignature) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuorumSignature.ProtoReflect.Descriptor instead.
func (*QuorumSignature) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{13}
}

func (m *QuorumSignature) GetSig() isQuorumSignature_Sig {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (x *QuorumSignature) GetECDSASigs() *ECDSAMultiSignature {
	if x, ok := x.GetSig().(*QuorumSignature_ECDSASigs); ok {
		return x.ECDSASigs
	}
	return nil
}

func (x *QuorumSignature) GetBLS12Sig() *BLS12AggregateSignature {
	if x, ok := x.GetSig().(*QuorumSignature_BLS12Sig); ok {
		return x.BLS12Sig
	}
	return nil
}

func (x *QuorumSignature) GetEDDSASigs() *EDDSAMultiSignature {
	if x, ok := x.GetSig().(*QuorumSignature_EDDSASigs); ok {
		return x.EDDSASigs
	}
	return nil
}

type isQuorumSignature_Sig interface {
	isQuorumSignature_Sig()
}

type QuorumSignature_ECDSASigs struct {
	ECDSASigs *ECDSAMultiSignature `protobuf:"bytes,1,opt,name=ECDSASigs,proto3,oneof"`
}

type QuorumSignature_BLS12Sig struct {
	BLS12Sig *BLS12AggregateSignature `protobuf:"bytes,2,opt,name=BLS12Sig,proto3,oneof"`
}

type QuorumSignature_EDDSASigs struct {
	EDDSASigs *EDDSAMultiSignature `protobuf:"bytes,3,opt,name=EDDSASigs,proto3,oneof"`
}

func (*QuorumSignature_ECDSASigs) isQuorumSignature_Sig() {}

func (*QuorumSignature_BLS12Sig) isQuorumSignature_Sig() {}

func (*QuorumSignature_EDDSASigs) isQuorumSignature_Sig() {}

type QuorumCert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sig  *QuorumSignature `protobuf:"bytes,1,opt,name=Sig,proto3" json:"Sig,omitempty"`
	View uint64           `protobuf:"varint,2,opt,name=View,proto3" json:"View,omitempty"`
	Hash []byte           `protobuf:"bytes,3,opt,name=Hash,proto3" json:"Hash,omitempty"`
}

func (x *QuorumCert) Reset() {
	*x = QuorumCert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuorumCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumCert) ProtoMessage() {}

func (x *QuorumCert) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuorumCert.ProtoReflect.Descriptor instead.
func (*QuorumCert) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{14}
}

func (x *QuorumCert) GetSig() *QuorumSignature {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *QuorumCert) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *QuorumCert) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type TimeoutCert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sig  *QuorumSignature `protobuf:"bytes,1,opt,name=Sig,proto3" json:"Sig,omitempty"`
	View uint64           `protobuf:"varint,2,opt,name=View,proto3" json:"View,omitempty"`
}

func (x *TimeoutCert) Reset() {
	*x = TimeoutCert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeoutCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutCert) ProtoMessage() {}

func (x *TimeoutCert) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutCert.ProtoReflect.Descriptor instead.
func (*TimeoutCert) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{15}
}

func (x *TimeoutCert) GetSig() *QuorumSignature {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *TimeoutCert) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

type TimeoutMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	View     uint64           `protobuf:"varint,1,opt,name=View,proto3" json:"View,omitempty"`
	SyncInfo *SyncInfo        `protobuf:"bytes,2,opt,name=SyncInfo,proto3" json:"SyncInfo,omitempty"`
	ViewSig  *QuorumSignature `protobuf:"bytes,3,opt,name=ViewSig,proto3" json:"ViewSig,omitempty"`
	MsgSig   *QuorumSignature `protobuf:"bytes,4,opt,name=MsgSig,proto3" json:"MsgSig,omitempty"`
}

func (x *TimeoutMsg) Reset() {
	*x = TimeoutMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeoutMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutMsg) ProtoMessage() {}

func (x *TimeoutMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutMsg.ProtoReflect.Descriptor instead.
func (*TimeoutMsg) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{16}
}

func (x *TimeoutMsg) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *TimeoutMsg) GetSyncInfo() *SyncInfo {
	if x != nil {
		return x.SyncInfo
	}
	return nil
}

func (x *TimeoutMsg) GetViewSig() *QuorumSignature {
	if x != nil {
		return x.ViewSig
	}
	return nil
}

func (x *TimeoutMsg) GetMsgSig() *QuorumSignature {
	if x != nil {
		return x.MsgSig
	}
	return nil
}

type SyncInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QC    *QuorumCert  `protobuf:"bytes,1,opt,name=QC,proto3" json:"QC,omitempty"`
	TC    *TimeoutCert `protobuf:"bytes,2,opt,name=TC,proto3" json:"TC,omitempty"`
	AggQC *AggQC       `protobuf:"bytes,3,opt,name=AggQC,proto3" json:"AggQC,omitempty"`
}

func (x *SyncInfo) Reset() {
	*x = SyncInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncInfo) ProtoMessage() {}

func (x *SyncInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncInfo.ProtoReflect.Descriptor instead.
func (*SyncInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{17}
}

func (x *SyncInfo) GetQC() *QuorumCert {
	if x != nil {
		return x.QC
	}
	return nil
}

func (x *SyncInfo) GetTC() *TimeoutCert {
	if x != nil {
		return x.TC
	}
	return nil
}

func (x *SyncInfo) GetAggQC() *AggQC {
	if x != nil {
		return x.AggQC
	}
	return nil
}

type AggQC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QCs  map[uint32]*QuorumCert `protobuf:"bytes,1,rep,name=QCs,proto3" json:"QCs,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Sig  *QuorumSignature       `protobuf:"bytes,2,opt,name=Sig,proto3" json:"Sig,omitempty"`
	View uint64                 `protobuf:"varint,3,opt,name=View,proto3" json:"View,omitempty"`
}

func (x *AggQC) Reset() {
	*x = AggQC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AggQC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggQC) ProtoMessage() {}

func (x *AggQC) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggQC.ProtoReflect.Descriptor instead.
func (*AggQC) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{18}
}

func (x *AggQC) GetQCs() map[uint32]*QuorumCert {
	if x != nil {
		return x.QCs
	}
	return nil
}

func (x *AggQC) GetSig() *QuorumSignature {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *AggQC) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

var File_internal_proto_hotstuffpb_hotstuff_proto protoreflect.FileDescriptor

var file_internal_proto_hotstuffpb_hotstuff_proto_rawDesc = []byte{
	0x0a, 0x28, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2f, 0x68, 0x6f, 0x74, 0x73,
	0x74, 0x75, 0x66, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x68, 0x6f, 0x74, 0x73,
	0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x1a, 0x0c, 0x67, 0x6f, 0x72, 0x75, 0x6d, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x58, 0x0a, 0x19, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x42, 0x75, 0x6e,
	0x64, 0x6c, 0x65, 0x4f, 0x66, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x73, 0x12, 0x3b,
	0x0a, 0x09, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x50,
	0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c,
	0x52, 0x09, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x73, 0x22, 0x65, 0x0a, 0x11, 0x50,
	0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c,
	0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x64,
	0x12, 0x30, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e,
	0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x52, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73,
	0x61, 0x6c, 0x22, 0x5c, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x12, 0x27,
	0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x52, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x27, 0x0a, 0x05, 0x41, 0x67, 0x67, 0x51, 0x43,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66,
	0x66, 0x70, 0x62, 0x2e, 0x41, 0x67, 0x67, 0x51, 0x43, 0x52, 0x05, 0x41, 0x67, 0x67, 0x51, 0x43,
	0x22, 0x1f, 0x0a, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a,
	0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x48, 0x61, 0x73,
	0x68, 0x22, 0x91, 0x01, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x50,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x50, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x02, 0x51, 0x43, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x6f,
	0x72, 0x75, 0x6d, 0x43, 0x65, 0x72, 0x74, 0x52, 0x02, 0x51, 0x43, 0x12, 0x12, 0x0a, 0x04, 0x56,
	0x69, 0x65, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x56, 0x69, 0x65, 0x77, 0x12,
	0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x72, 0x6f,
	0x70, 0x6f, 0x73, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x50, 0x72, 0x6f,
	0x70, 0x6f, 0x73, 0x65, 0x72, 0x22, 0x44, 0x0a, 0x0e, 0x45, 0x43, 0x44, 0x53, 0x41, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x12,
	0x0c, 0x0a, 0x01, 0x52, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x52, 0x12, 0x0c, 0x0a,
	0x01, 0x53, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x53, 0x22, 0x22, 0x0a, 0x0e, 0x42,
	0x4c, 0x53, 0x31, 0x32, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x53, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x53, 0x69, 0x67, 0x22,
	0x3a, 0x0a, 0x0e, 0x45, 0x44, 0x44, 0x53, 0x41, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x69, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x53, 0x69, 0x67, 0x22, 0xc0, 0x01, 0x0a, 0x09,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x38, 0x0a, 0x08, 0x45, 0x43, 0x44,
	0x53, 0x41, 0x53, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x68, 0x6f,
	0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x45, 0x43, 0x44, 0x53, 0x41, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x48, 0x00, 0x52, 0x08, 0x45, 0x43, 0x44, 0x53, 0x41,
	0x53, 0x69, 0x67, 0x12, 0x38, 0x0a, 0x08, 0x42, 0x4c, 0x53, 0x31, 0x32, 0x53, 0x69, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66,
	0x70, 0x62, 0x2e, 0x42, 0x4c, 0x53, 0x31, 0x32, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x48, 0x00, 0x52, 0x08, 0x42, 0x4c, 0x53, 0x31, 0x32, 0x53, 0x69, 0x67, 0x12, 0x38, 0x0a,
	0x08, 0x45, 0x44, 0x44, 0x53, 0x41, 0x53, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x45, 0x44, 0x44,
	0x53, 0x41, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x48, 0x00, 0x52, 0x08, 0x45,
	0x44, 0x44, 0x53, 0x41, 0x53, 0x69, 0x67, 0x42, 0x05, 0x0a, 0x03, 0x53, 0x69, 0x67, 0x22, 0x50,
	0x0a, 0x0b, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x43, 0x65, 0x72, 0x74, 0x12, 0x2d, 0x0a,
	0x03, 0x53, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x68, 0x6f, 0x74,
	0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x03, 0x53, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68,
	0x22, 0x45, 0x0a, 0x13, 0x45, 0x43, 0x44, 0x53, 0x41, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x53, 0x69, 0x67, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66,
	0x70, 0x62, 0x2e, 0x45, 0x43, 0x44, 0x53, 0x41, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x52, 0x04, 0x53, 0x69, 0x67, 0x73, 0x22, 0x45, 0x0a, 0x13, 0x45, 0x44, 0x44, 0x53, 0x41,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x2e,
	0x0a, 0x04, 0x53, 0x69, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x68,
	0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x45, 0x44, 0x44, 0x53, 0x41, 0x53,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x04, 0x53, 0x69, 0x67, 0x73, 0x22, 0x4f,
	0x0a, 0x17, 0x42, 0x4c, 0x53, 0x31, 0x32, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x69, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x53, 0x69, 0x67, 0x12, 0x22, 0x0a, 0x0c, 0x70,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0c, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x73, 0x22,
	0xdd, 0x01, 0x0a, 0x0f, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x12, 0x3f, 0x0a, 0x09, 0x45, 0x43, 0x44, 0x53, 0x41, 0x53, 0x69, 0x67, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66,
	0x66, 0x70, 0x62, 0x2e, 0x45, 0x43, 0x44, 0x53, 0x41, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x48, 0x00, 0x52, 0x09, 0x45, 0x43, 0x44, 0x53, 0x41,
	0x53, 0x69, 0x67, 0x73, 0x12, 0x41, 0x0a, 0x08, 0x42, 0x4c, 0x53, 0x31, 0x32, 0x53, 0x69, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66,
	0x66, 0x70, 0x62, 0x2e, 0x42, 0x4c, 0x53, 0x31, 0x32, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61,
	0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x48, 0x00, 0x52, 0x08, 0x42,
	0x4c, 0x53, 0x31, 0x32, 0x53, 0x69, 0x67, 0x12, 0x3f, 0x0a, 0x09, 0x45, 0x44, 0x44, 0x53, 0x41,
	0x53, 0x69, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x68, 0x6f, 0x74,
	0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x45, 0x44, 0x44, 0x53, 0x41, 0x4d, 0x75, 0x6c,
	0x74, 0x69, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x48, 0x00, 0x52, 0x09, 0x45,
	0x44, 0x44, 0x53, 0x41, 0x53, 0x69, 0x67, 0x73, 0x42, 0x05, 0x0a, 0x03, 0x53, 0x69, 0x67, 0x22,
	0x63, 0x0a, 0x0a, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x43, 0x65, 0x72, 0x74, 0x12, 0x2d, 0x0a,
	0x03, 0x53, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x68, 0x6f, 0x74,
	0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x03, 0x53, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x56, 0x69, 0x65, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x56, 0x69, 0x65, 0x77,
	0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x48, 0x61, 0x73, 0x68, 0x22, 0x50, 0x0a, 0x0b, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x43,
	0x65, 0x72, 0x74, 0x12, 0x2d, 0x0a, 0x03, 0x53, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x51, 0x75,
	0x6f, 0x72, 0x75, 0x6d, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x03, 0x53,
	0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x56, 0x69, 0x65, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x04, 0x56, 0x69, 0x65, 0x77, 0x22, 0xbe, 0x01, 0x0a, 0x0a, 0x54, 0x69, 0x6d, 0x65, 0x6f,
	0x75, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x56, 0x69, 0x65, 0x77, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x04, 0x56, 0x69, 0x65, 0x77, 0x12, 0x30, 0x0a, 0x08, 0x53, 0x79, 0x6e,
	0x63, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x68, 0x6f,
	0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x08, 0x53, 0x79, 0x6e, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x35, 0x0a, 0x07, 0x56,
	0x69, 0x65, 0x77, 0x53, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x68,
	0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x07, 0x56, 0x69, 0x65, 0x77, 0x53,
	0x69, 0x67, 0x12, 0x33, 0x0a, 0x06, 0x4d, 0x73, 0x67, 0x53, 0x69, 0x67, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e,
	0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52,
	0x06, 0x4d, 0x73, 0x67, 0x53, 0x69, 0x67, 0x22, 0x84, 0x01, 0x0a, 0x08, 0x53, 0x79, 0x6e, 0x63,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x26, 0x0a, 0x02, 0x51, 0x43, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x51, 0x75,
	0x6f, 0x72, 0x75, 0x6d, 0x43, 0x65, 0x72, 0x74, 0x52, 0x02, 0x51, 0x43, 0x12, 0x27, 0x0a, 0x02,
	0x54, 0x43, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74,
	0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x43, 0x65, 0x72,
	0x74, 0x52, 0x02, 0x54, 0x43, 0x12, 0x27, 0x0a, 0x05, 0x41, 0x67, 0x67, 0x51, 0x43, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70,
	0x62, 0x2e, 0x41, 0x67, 0x67, 0x51, 0x43, 0x52, 0x05, 0x41, 0x67, 0x67, 0x51, 0x43, 0x22, 0xc8,
	0x01, 0x0a, 0x05, 0x41, 0x67, 0x67, 0x51, 0x43, 0x12, 0x2c, 0x0a, 0x03, 0x51, 0x43, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66,
	0x70, 0x62, 0x2e, 0x41, 0x67, 0x67, 0x51, 0x43, 0x2e, 0x51, 0x43, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x03, 0x51, 0x43, 0x73, 0x12, 0x2d, 0x0a, 0x03, 0x53, 0x69, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62,
	0x2e, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x52, 0x03, 0x53, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x56, 0x69, 0x65, 0x77, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x04, 0x56, 0x69, 0x65, 0x77, 0x1a, 0x4e, 0x0a, 0x08, 0x51, 0x43, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66,
	0x66, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x43, 0x65, 0x72, 0x74, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0x99, 0x03, 0x0a, 0x08, 0x48, 0x6f,
	0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x12, 0x3d, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73,
	0x65, 0x12, 0x14, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x50,
	0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x04, 0x98, 0xb5, 0x18, 0x01, 0x12, 0x3d, 0x0a, 0x04, 0x56, 0x6f, 0x74, 0x65, 0x12, 0x17, 0x2e,
	0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69,
	0x61, 0x6c, 0x43, 0x65, 0x72, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x04,
	0x90, 0xb5, 0x18, 0x01, 0x12, 0x3f, 0x0a, 0x07, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12,
	0x16, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x6f, 0x75, 0x74, 0x4d, 0x73, 0x67, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x04, 0x98, 0xb5, 0x18, 0x01, 0x12, 0x3d, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x56, 0x69, 0x65, 0x77,
	0x12, 0x14, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x53, 0x79,
	0x6e, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x04,
	0x90, 0xb5, 0x18, 0x01, 0x12, 0x37, 0x0a, 0x05, 0x46, 0x65, 0x74, 0x63, 0x68, 0x12, 0x15, 0x2e,
	0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x48, 0x61, 0x73, 0x68, 0x1a, 0x11, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70,
	0x62, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x04, 0xa0, 0xb5, 0x18, 0x01, 0x12, 0x56, 0x0a,
	0x0f, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65,
	0x12, 0x25, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x50, 0x69,
	0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x4f, 0x66, 0x50, 0x72,
	0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x73, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x04, 0x98, 0xb5, 0x18, 0x01, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x6c, 0x61, 0x62, 0x2f, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75,
	0x66, 0x66, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_hotstuffpb_hotstuff_proto_rawDescOnce sync.Once
	file_internal_proto_hotstuffpb_hotstuff_proto_rawDescData = file_internal_proto_hotstuffpb_hotstuff_proto_rawDesc
)

func file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP() []byte {
	file_internal_proto_hotstuffpb_hotstuff_proto_rawDescOnce.Do(func() {
		file_internal_proto_hotstuffpb_hotstuff_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_hotstuffpb_hotstuff_proto_rawDescData)
	})
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescData
}

var file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_internal_proto_hotstuffpb_hotstuff_proto_goTypes = []any{
	(*PipelineBundleOfProposals)(nil), // 0: hotstuffpb.PipelineBundleOfProposals
	(*PipelinedProposal)(nil),         // 1: hotstuffpb.PipelinedProposal
	(*Proposal)(nil),                  // 2: hotstuffpb.Proposal
	(*BlockHash)(nil),                 // 3: hotstuffpb.BlockHash
	(*Block)(nil),                     // 4: hotstuffpb.Block
	(*ECDSASignature)(nil),            // 5: hotstuffpb.ECDSASignature
	(*BLS12Signature)(nil),            // 6: hotstuffpb.BLS12Signature
	(*EDDSASignature)(nil),            // 7: hotstuffpb.EDDSASignature
	(*Signature)(nil),                 // 8: hotstuffpb.Signature
	(*PartialCert)(nil),               // 9: hotstuffpb.PartialCert
	(*ECDSAMultiSignature)(nil),       // 10: hotstuffpb.ECDSAMultiSignature
	(*EDDSAMultiSignature)(nil),       // 11: hotstuffpb.EDDSAMultiSignature
	(*BLS12AggregateSignature)(nil),   // 12: hotstuffpb.BLS12AggregateSignature
	(*QuorumSignature)(nil),           // 13: hotstuffpb.QuorumSignature
	(*QuorumCert)(nil),                // 14: hotstuffpb.QuorumCert
	(*TimeoutCert)(nil),               // 15: hotstuffpb.TimeoutCert
	(*TimeoutMsg)(nil),                // 16: hotstuffpb.TimeoutMsg
	(*SyncInfo)(nil),                  // 17: hotstuffpb.SyncInfo
	(*AggQC)(nil),                     // 18: hotstuffpb.AggQC
	nil,                               // 19: hotstuffpb.AggQC.QCsEntry
	(*emptypb.Empty)(nil),             // 20: google.protobuf.Empty
}
var file_internal_proto_hotstuffpb_hotstuff_proto_depIdxs = []int32{
	1,  // 0: hotstuffpb.PipelineBundleOfProposals.Proposals:type_name -> hotstuffpb.PipelinedProposal
	2,  // 1: hotstuffpb.PipelinedProposal.Proposal:type_name -> hotstuffpb.Proposal
	4,  // 2: hotstuffpb.Proposal.Block:type_name -> hotstuffpb.Block
	18, // 3: hotstuffpb.Proposal.AggQC:type_name -> hotstuffpb.AggQC
	14, // 4: hotstuffpb.Block.QC:type_name -> hotstuffpb.QuorumCert
	5,  // 5: hotstuffpb.Signature.ECDSASig:type_name -> hotstuffpb.ECDSASignature
	6,  // 6: hotstuffpb.Signature.BLS12Sig:type_name -> hotstuffpb.BLS12Signature
	7,  // 7: hotstuffpb.Signature.EDDSASig:type_name -> hotstuffpb.EDDSASignature
	13, // 8: hotstuffpb.PartialCert.Sig:type_name -> hotstuffpb.QuorumSignature
	5,  // 9: hotstuffpb.ECDSAMultiSignature.Sigs:type_name -> hotstuffpb.ECDSASignature
	7,  // 10: hotstuffpb.EDDSAMultiSignature.Sigs:type_name -> hotstuffpb.EDDSASignature
	10, // 11: hotstuffpb.QuorumSignature.ECDSASigs:type_name -> hotstuffpb.ECDSAMultiSignature
	12, // 12: hotstuffpb.QuorumSignature.BLS12Sig:type_name -> hotstuffpb.BLS12AggregateSignature
	11, // 13: hotstuffpb.QuorumSignature.EDDSASigs:type_name -> hotstuffpb.EDDSAMultiSignature
	13, // 14: hotstuffpb.QuorumCert.Sig:type_name -> hotstuffpb.QuorumSignature
	13, // 15: hotstuffpb.TimeoutCert.Sig:type_name -> hotstuffpb.QuorumSignature
	17, // 16: hotstuffpb.TimeoutMsg.SyncInfo:type_name -> hotstuffpb.SyncInfo
	13, // 17: hotstuffpb.TimeoutMsg.ViewSig:type_name -> hotstuffpb.QuorumSignature
	13, // 18: hotstuffpb.TimeoutMsg.MsgSig:type_name -> hotstuffpb.QuorumSignature
	14, // 19: hotstuffpb.SyncInfo.QC:type_name -> hotstuffpb.QuorumCert
	15, // 20: hotstuffpb.SyncInfo.TC:type_name -> hotstuffpb.TimeoutCert
	18, // 21: hotstuffpb.SyncInfo.AggQC:type_name -> hotstuffpb.AggQC
	19, // 22: hotstuffpb.AggQC.QCs:type_name -> hotstuffpb.AggQC.QCsEntry
	13, // 23: hotstuffpb.AggQC.Sig:type_name -> hotstuffpb.QuorumSignature
	14, // 24: hotstuffpb.AggQC.QCsEntry.value:type_name -> hotstuffpb.QuorumCert
	2,  // 25: hotstuffpb.Hotstuff.Propose:input_type -> hotstuffpb.Proposal
	9,  // 26: hotstuffpb.Hotstuff.Vote:input_type -> hotstuffpb.PartialCert
	16, // 27: hotstuffpb.Hotstuff.Timeout:input_type -> hotstuffpb.TimeoutMsg
	17, // 28: hotstuffpb.Hotstuff.NewView:input_type -> hotstuffpb.SyncInfo
	3,  // 29: hotstuffpb.Hotstuff.Fetch:input_type -> hotstuffpb.BlockHash
	0,  // 30: hotstuffpb.Hotstuff.PipelinePropose:input_type -> hotstuffpb.PipelineBundleOfProposals
	20, // 31: hotstuffpb.Hotstuff.Propose:output_type -> google.protobuf.Empty
	20, // 32: hotstuffpb.Hotstuff.Vote:output_type -> google.protobuf.Empty
	20, // 33: hotstuffpb.Hotstuff.Timeout:output_type -> google.protobuf.Empty
	20, // 34: hotstuffpb.Hotstuff.NewView:output_type -> google.protobuf.Empty
	4,  // 35: hotstuffpb.Hotstuff.Fetch:output_type -> hotstuffpb.Block
	20, // 36: hotstuffpb.Hotstuff.PipelinePropose:output_type -> google.protobuf.Empty
	31, // [31:37] is the sub-list for method output_type
	25, // [25:31] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_internal_proto_hotstuffpb_hotstuff_proto_init() }
func file_internal_proto_hotstuffpb_hotstuff_proto_init() {
	if File_internal_proto_hotstuffpb_hotstuff_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PipelineBundleOfProposals); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*PipelinedProposal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Proposal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*BlockHash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ECDSASignature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*BLS12Signature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*EDDSASignature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*Signature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*PartialCert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ECDSAMultiSignature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*EDDSAMultiSignature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*BLS12AggregateSignature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*QuorumSignature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*QuorumCert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*TimeoutCert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*TimeoutMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*SyncInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*AggQC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[8].OneofWrappers = []any{
		(*Signature_ECDSASig)(nil),
		(*Signature_BLS12Sig)(nil),
		(*Signature_EDDSASig)(nil),
	}
	file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[13].OneofWrappers = []any{
		(*QuorumSignature_ECDSASigs)(nil),
		(*QuorumSignature_BLS12Sig)(nil),
		(*QuorumSignature_EDDSASigs)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_hotstuffpb_hotstuff_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_hotstuffpb_hotstuff_proto_goTypes,
		DependencyIndexes: file_internal_proto_hotstuffpb_hotstuff_proto_depIdxs,
		MessageInfos:      file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes,
	}.Build()
	File_internal_proto_hotstuffpb_hotstuff_proto = out.File
	file_internal_proto_hotstuffpb_hotstuff_proto_rawDesc = nil
	file_internal_proto_hotstuffpb_hotstuff_proto_goTypes = nil
	file_internal_proto_hotstuffpb_hotstuff_proto_depIdxs = nil
}
