// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v6.30.2
// source: internal/proto/hotstuffpb/hotstuff.proto

package hotstuffpb

import (
	_ "github.com/relab/gorums"
	clientpb "github.com/relab/hotstuff/internal/proto/clientpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Proposal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *Block                 `protobuf:"bytes,1,opt,name=Block,proto3" json:"Block,omitempty"`
	AggQC         *AggQC                 `protobuf:"bytes,2,opt,name=AggQC,proto3" json:"AggQC,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proposal) Reset() {
	*x = Proposal{}
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposal) ProtoMessage() {}

func (x *Proposal) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proposal.ProtoReflect.Descriptor instead.
func (*Proposal) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{0}
}

func (x *Proposal) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *Proposal) GetAggQC() *AggQC {
	if x != nil {
		return x.AggQC
	}
	return nil
}

type BlockHash struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockHash) Reset() {
	*x = BlockHash{}
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHash) ProtoMessage() {}

func (x *BlockHash) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHash.ProtoReflect.Descriptor instead.
func (*BlockHash) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{1}
}

func (x *BlockHash) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        []byte                 `protobuf:"bytes,1,opt,name=Parent,proto3" json:"Parent,omitempty"`
	QC            *QuorumCert            `protobuf:"bytes,2,opt,name=QC,proto3" json:"QC,omitempty"`
	View          uint64                 `protobuf:"varint,3,opt,name=View,proto3" json:"View,omitempty"`
	Commands      *clientpb.Batch        `protobuf:"bytes,4,opt,name=Commands,proto3" json:"Commands,omitempty"`
	Proposer      uint32                 `protobuf:"varint,5,opt,name=Proposer,proto3" json:"Proposer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{2}
}

func (x *Block) GetParent() []byte {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *Block) GetQC() *QuorumCert {
	if x != nil {
		return x.QC
	}
	return nil
}

func (x *Block) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *Block) GetCommands() *clientpb.Batch {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *Block) GetProposer() uint32 {
	if x != nil {
		return x.Proposer
	}
	return 0
}

type ECDSASignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signer        uint32                 `protobuf:"varint,1,opt,name=Signer,proto3" json:"Signer,omitempty"`
	R             []byte                 `protobuf:"bytes,2,opt,name=R,proto3" json:"R,omitempty"`
	S             []byte                 `protobuf:"bytes,3,opt,name=S,proto3" json:"S,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ECDSASignature) Reset() {
	*x = ECDSASignature{}
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ECDSASignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECDSASignature) ProtoMessage() {}

func (x *ECDSASignature) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECDSASignature.ProtoReflect.Descriptor instead.
func (*ECDSASignature) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{3}
}

func (x *ECDSASignature) GetSigner() uint32 {
	if x != nil {
		return x.Signer
	}
	return 0
}

func (x *ECDSASignature) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *ECDSASignature) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

type BLS12Signature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sig           []byte                 `protobuf:"bytes,1,opt,name=Sig,proto3" json:"Sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BLS12Signature) Reset() {
	*x = BLS12Signature{}
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BLS12Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BLS12Signature) ProtoMessage() {}

func (x *BLS12Signature) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BLS12Signature.ProtoReflect.Descriptor instead.
func (*BLS12Signature) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{4}
}

func (x *BLS12Signature) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type EDDSASignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signer        uint32                 `protobuf:"varint,1,opt,name=Signer,proto3" json:"Signer,omitempty"`
	Sig           []byte                 `protobuf:"bytes,2,opt,name=Sig,proto3" json:"Sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EDDSASignature) Reset() {
	*x = EDDSASignature{}
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EDDSASignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EDDSASignature) ProtoMessage() {}

func (x *EDDSASignature) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EDDSASignature.ProtoReflect.Descriptor instead.
func (*EDDSASignature) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{5}
}

func (x *EDDSASignature) GetSigner() uint32 {
	if x != nil {
		return x.Signer
	}
	return 0
}

func (x *EDDSASignature) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type Signature struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Sig:
	//
	//	*Signature_ECDSASig
	//	*Signature_BLS12Sig
	//	*Signature_EDDSASig
	Sig           isSignature_Sig `protobuf_oneof:"Sig"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{6}
}

func (x *Signature) GetSig() isSignature_Sig {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *Signature) GetECDSASig() *ECDSASignature {
	if x != nil {
		if x, ok := x.Sig.(*Signature_ECDSASig); ok {
			return x.ECDSASig
		}
	}
	return nil
}

func (x *Signature) GetBLS12Sig() *BLS12Signature {
	if x != nil {
		if x, ok := x.Sig.(*Signature_BLS12Sig); ok {
			return x.BLS12Sig
		}
	}
	return nil
}

func (x *Signature) GetEDDSASig() *EDDSASignature {
	if x != nil {
		if x, ok := x.Sig.(*Signature_EDDSASig); ok {
			return x.EDDSASig
		}
	}
	return nil
}

type isSignature_Sig interface {
	isSignature_Sig()
}

type Signature_ECDSASig struct {
	ECDSASig *ECDSASignature `protobuf:"bytes,1,opt,name=ECDSASig,proto3,oneof"`
}

type Signature_BLS12Sig struct {
	BLS12Sig *BLS12Signature `protobuf:"bytes,2,opt,name=BLS12Sig,proto3,oneof"`
}

type Signature_EDDSASig struct {
	EDDSASig *EDDSASignature `protobuf:"bytes,3,opt,name=EDDSASig,proto3,oneof"`
}

func (*Signature_ECDSASig) isSignature_Sig() {}

func (*Signature_BLS12Sig) isSignature_Sig() {}

func (*Signature_EDDSASig) isSignature_Sig() {}

type PartialCert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sig           *QuorumSignature       `protobuf:"bytes,1,opt,name=Sig,proto3" json:"Sig,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartialCert) Reset() {
	*x = PartialCert{}
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartialCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialCert) ProtoMessage() {}

func (x *PartialCert) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialCert.ProtoReflect.Descriptor instead.
func (*PartialCert) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{7}
}

func (x *PartialCert) GetSig() *QuorumSignature {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *PartialCert) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type ECDSAMultiSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sigs          []*ECDSASignature      `protobuf:"bytes,1,rep,name=Sigs,proto3" json:"Sigs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ECDSAMultiSignature) Reset() {
	*x = ECDSAMultiSignature{}
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ECDSAMultiSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECDSAMultiSignature) ProtoMessage() {}

func (x *ECDSAMultiSignature) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECDSAMultiSignature.ProtoReflect.Descriptor instead.
func (*ECDSAMultiSignature) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{8}
}

func (x *ECDSAMultiSignature) GetSigs() []*ECDSASignature {
	if x != nil {
		return x.Sigs
	}
	return nil
}

type EDDSAMultiSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sigs          []*EDDSASignature      `protobuf:"bytes,1,rep,name=Sigs,proto3" json:"Sigs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EDDSAMultiSignature) Reset() {
	*x = EDDSAMultiSignature{}
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EDDSAMultiSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EDDSAMultiSignature) ProtoMessage() {}

func (x *EDDSAMultiSignature) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EDDSAMultiSignature.ProtoReflect.Descriptor instead.
func (*EDDSAMultiSignature) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{9}
}

func (x *EDDSAMultiSignature) GetSigs() []*EDDSASignature {
	if x != nil {
		return x.Sigs
	}
	return nil
}

type BLS12AggregateSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sig           []byte                 `protobuf:"bytes,1,opt,name=Sig,proto3" json:"Sig,omitempty"`
	Participants  []byte                 `protobuf:"bytes,2,opt,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BLS12AggregateSignature) Reset() {
	*x = BLS12AggregateSignature{}
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BLS12AggregateSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BLS12AggregateSignature) ProtoMessage() {}

func (x *BLS12AggregateSignature) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BLS12AggregateSignature.ProtoReflect.Descriptor instead.
func (*BLS12AggregateSignature) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{10}
}

func (x *BLS12AggregateSignature) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *BLS12AggregateSignature) GetParticipants() []byte {
	if x != nil {
		return x.Participants
	}
	return nil
}

type QuorumSignature struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Sig:
	//
	//	*QuorumSignature_ECDSASigs
	//	*QuorumSignature_BLS12Sig
	//	*QuorumSignature_EDDSASigs
	Sig           isQuorumSignature_Sig `protobuf_oneof:"Sig"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuorumSignature) Reset() {
	*x = QuorumSignature{}
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuorumSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumSignature) ProtoMessage() {}

func (x *QuorumSignature) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuorumSignature.ProtoReflect.Descriptor instead.
func (*QuorumSignature) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{11}
}

func (x *QuorumSignature) GetSig() isQuorumSignature_Sig {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *QuorumSignature) GetECDSASigs() *ECDSAMultiSignature {
	if x != nil {
		if x, ok := x.Sig.(*QuorumSignature_ECDSASigs); ok {
			return x.ECDSASigs
		}
	}
	return nil
}

func (x *QuorumSignature) GetBLS12Sig() *BLS12AggregateSignature {
	if x != nil {
		if x, ok := x.Sig.(*QuorumSignature_BLS12Sig); ok {
			return x.BLS12Sig
		}
	}
	return nil
}

func (x *QuorumSignature) GetEDDSASigs() *EDDSAMultiSignature {
	if x != nil {
		if x, ok := x.Sig.(*QuorumSignature_EDDSASigs); ok {
			return x.EDDSASigs
		}
	}
	return nil
}

type isQuorumSignature_Sig interface {
	isQuorumSignature_Sig()
}

type QuorumSignature_ECDSASigs struct {
	ECDSASigs *ECDSAMultiSignature `protobuf:"bytes,1,opt,name=ECDSASigs,proto3,oneof"`
}

type QuorumSignature_BLS12Sig struct {
	BLS12Sig *BLS12AggregateSignature `protobuf:"bytes,2,opt,name=BLS12Sig,proto3,oneof"`
}

type QuorumSignature_EDDSASigs struct {
	EDDSASigs *EDDSAMultiSignature `protobuf:"bytes,3,opt,name=EDDSASigs,proto3,oneof"`
}

func (*QuorumSignature_ECDSASigs) isQuorumSignature_Sig() {}

func (*QuorumSignature_BLS12Sig) isQuorumSignature_Sig() {}

func (*QuorumSignature_EDDSASigs) isQuorumSignature_Sig() {}

type QuorumCert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sig           *QuorumSignature       `protobuf:"bytes,1,opt,name=Sig,proto3" json:"Sig,omitempty"`
	View          uint64                 `protobuf:"varint,2,opt,name=View,proto3" json:"View,omitempty"`
	Hash          []byte                 `protobuf:"bytes,3,opt,name=Hash,proto3" json:"Hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuorumCert) Reset() {
	*x = QuorumCert{}
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuorumCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumCert) ProtoMessage() {}

func (x *QuorumCert) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuorumCert.ProtoReflect.Descriptor instead.
func (*QuorumCert) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{12}
}

func (x *QuorumCert) GetSig() *QuorumSignature {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *QuorumCert) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *QuorumCert) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type TimeoutCert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sig           *QuorumSignature       `protobuf:"bytes,1,opt,name=Sig,proto3" json:"Sig,omitempty"`
	View          uint64                 `protobuf:"varint,2,opt,name=View,proto3" json:"View,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeoutCert) Reset() {
	*x = TimeoutCert{}
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeoutCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutCert) ProtoMessage() {}

func (x *TimeoutCert) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutCert.ProtoReflect.Descriptor instead.
func (*TimeoutCert) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{13}
}

func (x *TimeoutCert) GetSig() *QuorumSignature {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *TimeoutCert) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

type TimeoutMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          uint64                 `protobuf:"varint,1,opt,name=View,proto3" json:"View,omitempty"`
	SyncInfo      *SyncInfo              `protobuf:"bytes,2,opt,name=SyncInfo,proto3" json:"SyncInfo,omitempty"`
	ViewSig       *QuorumSignature       `protobuf:"bytes,3,opt,name=ViewSig,proto3" json:"ViewSig,omitempty"`
	MsgSig        *QuorumSignature       `protobuf:"bytes,4,opt,name=MsgSig,proto3" json:"MsgSig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeoutMsg) Reset() {
	*x = TimeoutMsg{}
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeoutMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutMsg) ProtoMessage() {}

func (x *TimeoutMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutMsg.ProtoReflect.Descriptor instead.
func (*TimeoutMsg) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{14}
}

func (x *TimeoutMsg) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *TimeoutMsg) GetSyncInfo() *SyncInfo {
	if x != nil {
		return x.SyncInfo
	}
	return nil
}

func (x *TimeoutMsg) GetViewSig() *QuorumSignature {
	if x != nil {
		return x.ViewSig
	}
	return nil
}

func (x *TimeoutMsg) GetMsgSig() *QuorumSignature {
	if x != nil {
		return x.MsgSig
	}
	return nil
}

type SyncInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QC            *QuorumCert            `protobuf:"bytes,1,opt,name=QC,proto3" json:"QC,omitempty"`
	TC            *TimeoutCert           `protobuf:"bytes,2,opt,name=TC,proto3" json:"TC,omitempty"`
	AggQC         *AggQC                 `protobuf:"bytes,3,opt,name=AggQC,proto3" json:"AggQC,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncInfo) Reset() {
	*x = SyncInfo{}
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncInfo) ProtoMessage() {}

func (x *SyncInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncInfo.ProtoReflect.Descriptor instead.
func (*SyncInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{15}
}

func (x *SyncInfo) GetQC() *QuorumCert {
	if x != nil {
		return x.QC
	}
	return nil
}

func (x *SyncInfo) GetTC() *TimeoutCert {
	if x != nil {
		return x.TC
	}
	return nil
}

func (x *SyncInfo) GetAggQC() *AggQC {
	if x != nil {
		return x.AggQC
	}
	return nil
}

type AggQC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QCs           map[uint32]*QuorumCert `protobuf:"bytes,1,rep,name=QCs,proto3" json:"QCs,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Sig           *QuorumSignature       `protobuf:"bytes,2,opt,name=Sig,proto3" json:"Sig,omitempty"`
	View          uint64                 `protobuf:"varint,3,opt,name=View,proto3" json:"View,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggQC) Reset() {
	*x = AggQC{}
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggQC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggQC) ProtoMessage() {}

func (x *AggQC) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggQC.ProtoReflect.Descriptor instead.
func (*AggQC) Descriptor() ([]byte, []int) {
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP(), []int{16}
}

func (x *AggQC) GetQCs() map[uint32]*QuorumCert {
	if x != nil {
		return x.QCs
	}
	return nil
}

func (x *AggQC) GetSig() *QuorumSignature {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *AggQC) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

var File_internal_proto_hotstuffpb_hotstuff_proto protoreflect.FileDescriptor

var file_internal_proto_hotstuffpb_hotstuff_proto_rawDesc = []byte{
	0x0a, 0x28, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2f, 0x68, 0x6f, 0x74, 0x73,
	0x74, 0x75, 0x66, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x68, 0x6f, 0x74, 0x73,
	0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x1a, 0x0c, 0x67, 0x6f, 0x72, 0x75, 0x6d, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x24, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5c, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x6f,
	0x73, 0x61, 0x6c, 0x12, 0x27, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x27, 0x0a, 0x05,
	0x41, 0x67, 0x67, 0x51, 0x43, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x6f,
	0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x41, 0x67, 0x67, 0x51, 0x43, 0x52, 0x05,
	0x41, 0x67, 0x67, 0x51, 0x43, 0x22, 0x1f, 0x0a, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x22, 0xa4, 0x01, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x12, 0x16, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x02, 0x51, 0x43, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70,
	0x62, 0x2e, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x43, 0x65, 0x72, 0x74, 0x52, 0x02, 0x51, 0x43,
	0x12, 0x12, 0x0a, 0x04, 0x56, 0x69, 0x65, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04,
	0x56, 0x69, 0x65, 0x77, 0x12, 0x2b, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x70,
	0x62, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x22, 0x44, 0x0a,
	0x0e, 0x45, 0x43, 0x44, 0x53, 0x41, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x52, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x01, 0x52, 0x12, 0x0c, 0x0a, 0x01, 0x53, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x01, 0x53, 0x22, 0x22, 0x0a, 0x0e, 0x42, 0x4c, 0x53, 0x31, 0x32, 0x53, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x53, 0x69, 0x67, 0x22, 0x3a, 0x0a, 0x0e, 0x45, 0x44, 0x44, 0x53, 0x41,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x69, 0x67,
	0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65,
	0x72, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x53, 0x69, 0x67, 0x22, 0xc0, 0x01, 0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x12, 0x38, 0x0a, 0x08, 0x45, 0x43, 0x44, 0x53, 0x41, 0x53, 0x69, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62,
	0x2e, 0x45, 0x43, 0x44, 0x53, 0x41, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x48,
	0x00, 0x52, 0x08, 0x45, 0x43, 0x44, 0x53, 0x41, 0x53, 0x69, 0x67, 0x12, 0x38, 0x0a, 0x08, 0x42,
	0x4c, 0x53, 0x31, 0x32, 0x53, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x42, 0x4c, 0x53, 0x31, 0x32,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x48, 0x00, 0x52, 0x08, 0x42, 0x4c, 0x53,
	0x31, 0x32, 0x53, 0x69, 0x67, 0x12, 0x38, 0x0a, 0x08, 0x45, 0x44, 0x44, 0x53, 0x41, 0x53, 0x69,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75,
	0x66, 0x66, 0x70, 0x62, 0x2e, 0x45, 0x44, 0x44, 0x53, 0x41, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x48, 0x00, 0x52, 0x08, 0x45, 0x44, 0x44, 0x53, 0x41, 0x53, 0x69, 0x67, 0x42,
	0x05, 0x0a, 0x03, 0x53, 0x69, 0x67, 0x22, 0x50, 0x0a, 0x0b, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61,
	0x6c, 0x43, 0x65, 0x72, 0x74, 0x12, 0x2d, 0x0a, 0x03, 0x53, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e,
	0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52,
	0x03, 0x53, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x22, 0x45, 0x0a, 0x13, 0x45, 0x43, 0x44, 0x53,
	0x41, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12,
	0x2e, 0x0a, 0x04, 0x53, 0x69, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x45, 0x43, 0x44, 0x53, 0x41,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x04, 0x53, 0x69, 0x67, 0x73, 0x22,
	0x45, 0x0a, 0x13, 0x45, 0x44, 0x44, 0x53, 0x41, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x53, 0x69, 0x67, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70,
	0x62, 0x2e, 0x45, 0x44, 0x44, 0x53, 0x41, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x52, 0x04, 0x53, 0x69, 0x67, 0x73, 0x22, 0x4f, 0x0a, 0x17, 0x42, 0x4c, 0x53, 0x31, 0x32, 0x41,
	0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x53, 0x69, 0x67, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61,
	0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x70, 0x61, 0x72, 0x74, 0x69,
	0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x73, 0x22, 0xdd, 0x01, 0x0a, 0x0f, 0x51, 0x75, 0x6f, 0x72,
	0x75, 0x6d, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x3f, 0x0a, 0x09, 0x45,
	0x43, 0x44, 0x53, 0x41, 0x53, 0x69, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x45, 0x43, 0x44, 0x53,
	0x41, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x48,
	0x00, 0x52, 0x09, 0x45, 0x43, 0x44, 0x53, 0x41, 0x53, 0x69, 0x67, 0x73, 0x12, 0x41, 0x0a, 0x08,
	0x42, 0x4c, 0x53, 0x31, 0x32, 0x53, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x42, 0x4c, 0x53, 0x31,
	0x32, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x48, 0x00, 0x52, 0x08, 0x42, 0x4c, 0x53, 0x31, 0x32, 0x53, 0x69, 0x67, 0x12,
	0x3f, 0x0a, 0x09, 0x45, 0x44, 0x44, 0x53, 0x41, 0x53, 0x69, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e,
	0x45, 0x44, 0x44, 0x53, 0x41, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x48, 0x00, 0x52, 0x09, 0x45, 0x44, 0x44, 0x53, 0x41, 0x53, 0x69, 0x67, 0x73,
	0x42, 0x05, 0x0a, 0x03, 0x53, 0x69, 0x67, 0x22, 0x63, 0x0a, 0x0a, 0x51, 0x75, 0x6f, 0x72, 0x75,
	0x6d, 0x43, 0x65, 0x72, 0x74, 0x12, 0x2d, 0x0a, 0x03, 0x53, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e,
	0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52,
	0x03, 0x53, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x56, 0x69, 0x65, 0x77, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x04, 0x56, 0x69, 0x65, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x22, 0x50, 0x0a, 0x0b,
	0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x43, 0x65, 0x72, 0x74, 0x12, 0x2d, 0x0a, 0x03, 0x53,
	0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74,
	0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x53, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x03, 0x53, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x56, 0x69,
	0x65, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x56, 0x69, 0x65, 0x77, 0x22, 0xbe,
	0x01, 0x0a, 0x0a, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x56, 0x69, 0x65, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x56, 0x69, 0x65,
	0x77, 0x12, 0x30, 0x0a, 0x08, 0x53, 0x79, 0x6e, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62,
	0x2e, 0x53, 0x79, 0x6e, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x53, 0x79, 0x6e, 0x63, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x35, 0x0a, 0x07, 0x56, 0x69, 0x65, 0x77, 0x53, 0x69, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70,
	0x62, 0x2e, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x52, 0x07, 0x56, 0x69, 0x65, 0x77, 0x53, 0x69, 0x67, 0x12, 0x33, 0x0a, 0x06, 0x4d, 0x73,
	0x67, 0x53, 0x69, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x68, 0x6f, 0x74,
	0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x06, 0x4d, 0x73, 0x67, 0x53, 0x69, 0x67, 0x22,
	0x84, 0x01, 0x0a, 0x08, 0x53, 0x79, 0x6e, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x26, 0x0a, 0x02,
	0x51, 0x43, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74,
	0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x43, 0x65, 0x72, 0x74,
	0x52, 0x02, 0x51, 0x43, 0x12, 0x27, 0x0a, 0x02, 0x54, 0x43, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x43, 0x65, 0x72, 0x74, 0x52, 0x02, 0x54, 0x43, 0x12, 0x27, 0x0a,
	0x05, 0x41, 0x67, 0x67, 0x51, 0x43, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68,
	0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x41, 0x67, 0x67, 0x51, 0x43, 0x52,
	0x05, 0x41, 0x67, 0x67, 0x51, 0x43, 0x22, 0xc8, 0x01, 0x0a, 0x05, 0x41, 0x67, 0x67, 0x51, 0x43,
	0x12, 0x2c, 0x0a, 0x03, 0x51, 0x43, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x41, 0x67, 0x67, 0x51, 0x43,
	0x2e, 0x51, 0x43, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03, 0x51, 0x43, 0x73, 0x12, 0x2d,
	0x0a, 0x03, 0x53, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x68, 0x6f,
	0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x53,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x03, 0x53, 0x69, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x56, 0x69, 0x65, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x56, 0x69, 0x65,
	0x77, 0x1a, 0x4e, 0x0a, 0x08, 0x51, 0x43, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x6f, 0x72,
	0x75, 0x6d, 0x43, 0x65, 0x72, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x32, 0xc2, 0x02, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x12,
	0x3d, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x12, 0x14, 0x2e, 0x68, 0x6f, 0x74,
	0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x04, 0x98, 0xb5, 0x18, 0x01, 0x12, 0x3d,
	0x0a, 0x04, 0x56, 0x6f, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66,
	0x66, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x43, 0x65, 0x72, 0x74, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x04, 0x90, 0xb5, 0x18, 0x01, 0x12, 0x3f, 0x0a,
	0x07, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x16, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74,
	0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4d, 0x73, 0x67,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x04, 0x98, 0xb5, 0x18, 0x01, 0x12, 0x3d,
	0x0a, 0x07, 0x4e, 0x65, 0x77, 0x56, 0x69, 0x65, 0x77, 0x12, 0x14, 0x2e, 0x68, 0x6f, 0x74, 0x73,
	0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x04, 0x90, 0xb5, 0x18, 0x01, 0x12, 0x37, 0x0a,
	0x05, 0x46, 0x65, 0x74, 0x63, 0x68, 0x12, 0x15, 0x2e, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66,
	0x66, 0x70, 0x62, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x1a, 0x11, 0x2e,
	0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x22, 0x04, 0xa0, 0xb5, 0x18, 0x01, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x6c, 0x61, 0x62, 0x2f, 0x68, 0x6f, 0x74, 0x73, 0x74,
	0x75, 0x66, 0x66, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_hotstuffpb_hotstuff_proto_rawDescOnce sync.Once
	file_internal_proto_hotstuffpb_hotstuff_proto_rawDescData = file_internal_proto_hotstuffpb_hotstuff_proto_rawDesc
)

func file_internal_proto_hotstuffpb_hotstuff_proto_rawDescGZIP() []byte {
	file_internal_proto_hotstuffpb_hotstuff_proto_rawDescOnce.Do(func() {
		file_internal_proto_hotstuffpb_hotstuff_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_hotstuffpb_hotstuff_proto_rawDescData)
	})
	return file_internal_proto_hotstuffpb_hotstuff_proto_rawDescData
}

var file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_internal_proto_hotstuffpb_hotstuff_proto_goTypes = []any{
	(*Proposal)(nil),                // 0: hotstuffpb.Proposal
	(*BlockHash)(nil),               // 1: hotstuffpb.BlockHash
	(*Block)(nil),                   // 2: hotstuffpb.Block
	(*ECDSASignature)(nil),          // 3: hotstuffpb.ECDSASignature
	(*BLS12Signature)(nil),          // 4: hotstuffpb.BLS12Signature
	(*EDDSASignature)(nil),          // 5: hotstuffpb.EDDSASignature
	(*Signature)(nil),               // 6: hotstuffpb.Signature
	(*PartialCert)(nil),             // 7: hotstuffpb.PartialCert
	(*ECDSAMultiSignature)(nil),     // 8: hotstuffpb.ECDSAMultiSignature
	(*EDDSAMultiSignature)(nil),     // 9: hotstuffpb.EDDSAMultiSignature
	(*BLS12AggregateSignature)(nil), // 10: hotstuffpb.BLS12AggregateSignature
	(*QuorumSignature)(nil),         // 11: hotstuffpb.QuorumSignature
	(*QuorumCert)(nil),              // 12: hotstuffpb.QuorumCert
	(*TimeoutCert)(nil),             // 13: hotstuffpb.TimeoutCert
	(*TimeoutMsg)(nil),              // 14: hotstuffpb.TimeoutMsg
	(*SyncInfo)(nil),                // 15: hotstuffpb.SyncInfo
	(*AggQC)(nil),                   // 16: hotstuffpb.AggQC
	nil,                             // 17: hotstuffpb.AggQC.QCsEntry
	(*clientpb.Batch)(nil),          // 18: clientpb.Batch
	(*emptypb.Empty)(nil),           // 19: google.protobuf.Empty
}
var file_internal_proto_hotstuffpb_hotstuff_proto_depIdxs = []int32{
	2,  // 0: hotstuffpb.Proposal.Block:type_name -> hotstuffpb.Block
	16, // 1: hotstuffpb.Proposal.AggQC:type_name -> hotstuffpb.AggQC
	12, // 2: hotstuffpb.Block.QC:type_name -> hotstuffpb.QuorumCert
	18, // 3: hotstuffpb.Block.Commands:type_name -> clientpb.Batch
	3,  // 4: hotstuffpb.Signature.ECDSASig:type_name -> hotstuffpb.ECDSASignature
	4,  // 5: hotstuffpb.Signature.BLS12Sig:type_name -> hotstuffpb.BLS12Signature
	5,  // 6: hotstuffpb.Signature.EDDSASig:type_name -> hotstuffpb.EDDSASignature
	11, // 7: hotstuffpb.PartialCert.Sig:type_name -> hotstuffpb.QuorumSignature
	3,  // 8: hotstuffpb.ECDSAMultiSignature.Sigs:type_name -> hotstuffpb.ECDSASignature
	5,  // 9: hotstuffpb.EDDSAMultiSignature.Sigs:type_name -> hotstuffpb.EDDSASignature
	8,  // 10: hotstuffpb.QuorumSignature.ECDSASigs:type_name -> hotstuffpb.ECDSAMultiSignature
	10, // 11: hotstuffpb.QuorumSignature.BLS12Sig:type_name -> hotstuffpb.BLS12AggregateSignature
	9,  // 12: hotstuffpb.QuorumSignature.EDDSASigs:type_name -> hotstuffpb.EDDSAMultiSignature
	11, // 13: hotstuffpb.QuorumCert.Sig:type_name -> hotstuffpb.QuorumSignature
	11, // 14: hotstuffpb.TimeoutCert.Sig:type_name -> hotstuffpb.QuorumSignature
	15, // 15: hotstuffpb.TimeoutMsg.SyncInfo:type_name -> hotstuffpb.SyncInfo
	11, // 16: hotstuffpb.TimeoutMsg.ViewSig:type_name -> hotstuffpb.QuorumSignature
	11, // 17: hotstuffpb.TimeoutMsg.MsgSig:type_name -> hotstuffpb.QuorumSignature
	12, // 18: hotstuffpb.SyncInfo.QC:type_name -> hotstuffpb.QuorumCert
	13, // 19: hotstuffpb.SyncInfo.TC:type_name -> hotstuffpb.TimeoutCert
	16, // 20: hotstuffpb.SyncInfo.AggQC:type_name -> hotstuffpb.AggQC
	17, // 21: hotstuffpb.AggQC.QCs:type_name -> hotstuffpb.AggQC.QCsEntry
	11, // 22: hotstuffpb.AggQC.Sig:type_name -> hotstuffpb.QuorumSignature
	12, // 23: hotstuffpb.AggQC.QCsEntry.value:type_name -> hotstuffpb.QuorumCert
	0,  // 24: hotstuffpb.Consensus.Propose:input_type -> hotstuffpb.Proposal
	7,  // 25: hotstuffpb.Consensus.Vote:input_type -> hotstuffpb.PartialCert
	14, // 26: hotstuffpb.Consensus.Timeout:input_type -> hotstuffpb.TimeoutMsg
	15, // 27: hotstuffpb.Consensus.NewView:input_type -> hotstuffpb.SyncInfo
	1,  // 28: hotstuffpb.Consensus.Fetch:input_type -> hotstuffpb.BlockHash
	19, // 29: hotstuffpb.Consensus.Propose:output_type -> google.protobuf.Empty
	19, // 30: hotstuffpb.Consensus.Vote:output_type -> google.protobuf.Empty
	19, // 31: hotstuffpb.Consensus.Timeout:output_type -> google.protobuf.Empty
	19, // 32: hotstuffpb.Consensus.NewView:output_type -> google.protobuf.Empty
	2,  // 33: hotstuffpb.Consensus.Fetch:output_type -> hotstuffpb.Block
	29, // [29:34] is the sub-list for method output_type
	24, // [24:29] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_internal_proto_hotstuffpb_hotstuff_proto_init() }
func file_internal_proto_hotstuffpb_hotstuff_proto_init() {
	if File_internal_proto_hotstuffpb_hotstuff_proto != nil {
		return
	}
	file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[6].OneofWrappers = []any{
		(*Signature_ECDSASig)(nil),
		(*Signature_BLS12Sig)(nil),
		(*Signature_EDDSASig)(nil),
	}
	file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes[11].OneofWrappers = []any{
		(*QuorumSignature_ECDSASigs)(nil),
		(*QuorumSignature_BLS12Sig)(nil),
		(*QuorumSignature_EDDSASigs)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_hotstuffpb_hotstuff_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_hotstuffpb_hotstuff_proto_goTypes,
		DependencyIndexes: file_internal_proto_hotstuffpb_hotstuff_proto_depIdxs,
		MessageInfos:      file_internal_proto_hotstuffpb_hotstuff_proto_msgTypes,
	}.Build()
	File_internal_proto_hotstuffpb_hotstuff_proto = out.File
	file_internal_proto_hotstuffpb_hotstuff_proto_rawDesc = nil
	file_internal_proto_hotstuffpb_hotstuff_proto_goTypes = nil
	file_internal_proto_hotstuffpb_hotstuff_proto_depIdxs = nil
}
