# This is the information that each replica is given about the other replicas
pacemaker = "RR"
leaderSchedule = [1, 2, 3, 4]
termLength = 1

[[replicas]]
id = "1"
address = "127.0.0.1:13371"
keyfile = "keys/r1.key.pub"

[[replicas]]
id = "2"
address = "127.0.0.1:13372"
keyfile = "keys/r2.key.pub"

[[replicas]]
id = "3"
address = "127.0.0.1:13373"
keyfile = "keys/r3.key.pub"

[[replicas]]
id = "4"
address = "127.0.0.1:13374"
keyfile = "keys/r4.key.pub"
