FROM golang AS builder

WORKDIR /go/src/github.com/relab/hotstuff

# speed up the build by downloading the modules first
COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
RUN go install ./...

FROM ubuntu

RUN apt-get update
RUN apt-get install -y openssh-client

COPY --from=builder /go/bin/* /usr/bin/

WORKDIR /root
ADD scripts/id .ssh/
ADD scripts/id.pub .ssh/
ADD scripts/ssh_config .ssh/config
ADD scripts/example_config.toml ./example_config.toml
