FROM golang:alpine AS builder

WORKDIR /go/src/github.com/relab/hotstuff

# speed up the build by downloading the modules first
COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
RUN go install -ldflags='-s -w' ./...

FROM alpine

RUN apk add --no-cache --update openssh

COPY --from=builder /go/bin/* /usr/bin/

WORKDIR /root
ADD scripts/id .ssh/
ADD scripts/id.pub .ssh/
ADD scripts/ssh_config .ssh/config
