clients = 2
replicas = 4

#locations = ["Melbourne", "Rome", "Amsterdam", "Barcelona", "Gothenburg"]

# specific assignments for some hosts
[[hosts-config]]
name="localhost"
clients = 2
replicas = 4
location = "Melbourne"
